### ISSUE TITLE
Publish to PowerShell Gallery

### ISSUE THREAD

**Issue by megamorf** [Microsoft/ReportingServicesTools#1]
Hey guys,

I can see that the repo is fairly new which is probably the reason for the current installation procedure. Are you planning to integrate appveyor to publish it to the PS Gallery like PowerShell community resources, official Microsoft PowerShell and DSC modules do?

Thanks in advance,
Seb

**Comment by jtarquino** [comment]
Hi Seb, that sounds like a great idea, this started as a "side" project for some of the engineers inside the team, the idea is to make it better with the help of the community and automatic deployment from the repo to the gallery is something we would like to have in the future and we will consider the options including appveyor.

Thanks
