### ISSUE TITLE
Set-RsDatabase wmi error on SSRS 2017

### ISSUE THREAD

**Issue by HealisticEngineer** [Microsoft/ReportingServicesTools#104]
Seems to be a but when trying to use this with SSRS 2017
I run the command:
Set-RsDatabase -DatabaseServerName myserver\myinstance -Name reportingdb_new -DatabaseCredentialType Windows

And I'm presented with a WMI error.

Get-WmiObject : Invalid namespace "root\Microsoft\SqlServer\ReportServer\RS_MSSQLSERVER\v13\Admin"
At C:\Program Files\WindowsPowerShell\Modules\ReportingServicesTools\0.0.3.1\Functions\Utilities\New-RsConfigurationSet
tingObject.ps1:100 char:19
+     $wmiObjects = Get-WmiObject @getWmiObjectParameters
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand

In my setup I'm trying the SSRS 2017 on a clean server with SQL Server running on another clean server remotely the SQL Engine is 2016 Sp1 in case it matters.

I admit I could be running this module out of context.

**Comment by ClaudioESSilva** [comment]
Hi @HealisticEngineer ,

Can you please add the `-ReportServerVersion SQLServer2017` parameter to the command and see if it works?

It it is pointing to Get-WmiObject : Invalid namespace "root\Microsoft\SqlServer\ReportServer\RS_MSSQLSERVER\ **v13** \Admin" where it should be **v14**

**Comment by HealisticEngineer** [comment]
PS C:\WINDOWS\system32> Set-RsDatabase -DatabaseServerName myserver\myinstance -Name reportingdb_new -DatabaseCredentialType Windows -ReportServerVersion SQLServer2017

Confirm 
Are you sure you want to perform this action?
Performing the operation "Configure to use myserver\myinstance as database, using Windows authentication" on target "localhost (SQLServer2017) \ MSSQLSERVER".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y
Get-WmiObject : Invalid namespace "root\Microsoft\SqlServer\ReportServer\RS_MSSQLSERVER\v14\Admin"
At C:\Program Files\WindowsPowerShell\Modules\ReportingServicesTools\0.0.3.1\Functions\Utilities\New-RsConfigurationSet
tingObject.ps1:100 char:19
+     $wmiObjects = Get-WmiObject @getWmiObjectParameters
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand

**Comment by ClaudioESSilva** [comment]
> Get-WmiObject : Invalid namespace "root\Microsoft\SqlServer\ReportServer\RS_MSSQLSERVER\v14\Admin"
If you are using 2017 should not be `MSSQLSERVER`

Can you try to run this code:

Please change the variable `$ReportServerInstance` value if it is not the SSRS.
```
$ReportServerInstance = "SSRS"

$getWmiObjectParameters = @{
    ErrorAction = "Stop"
    Namespace = "root\Microsoft\SqlServer\ReportServer\RS_$ReportServerInstance\v14\Admin"
    Class = "MSReportServer_ConfigurationSetting"
}

Get-WmiObject @getWmiObjectParameters

```

**Comment by HealisticEngineer** [comment]
here's the responce

PS C:\WINDOWS\system32> $ReportServerInstance = "SSRS"
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32> $getWmiObjectParameters = @{
>>     ErrorAction = "Stop"
>>     Namespace = "root\Microsoft\SqlServer\ReportServer\RS_$ReportServerInstance\v14\Admin"
>>     Class = "MSReportServer_ConfigurationSetting"
>> }
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32> Get-WmiObject @getWmiObjectParameters


__GENUS                          : 2
__CLASS                          : MSReportServer_ConfigurationSetting
__SUPERCLASS                     :
__DYNASTY                        : MSReportServer_ConfigurationSetting
__RELPATH                        : MSReportServer_ConfigurationSetting.InstanceName="SSRS"
__PROPERTY_COUNT                 : 34
__DERIVATION                     : {}
__SERVER                         : SCW000002222
__NAMESPACE                      : root\Microsoft\SqlServer\ReportServer\RS_SSRS\v14\Admin
__PATH                           : \\SCW000002222\root\Microsoft\SqlServer\ReportServer\RS_SSRS\v14\Admin:MSReportServe
                                   r_ConfigurationSetting.InstanceName="SSRS"
ConnectionPoolSize               : 768
DatabaseLogonAccount             :
DatabaseLogonTimeout             : -1
DatabaseLogonType                : 2
DatabaseName                     :
DatabaseQueryTimeout             : 120
DatabaseServerName               :
ExtendedProtectionLevel          : Off
ExtendedProtectionScenario       : Proxy
FileShareAccount                 :
InstallationID                   : {70751a1a-1f93-4bfa-a14b-04623ed6215c}
InstanceName                     : SSRS
IsInitialized                    : False
IsPowerBIFeatureEnabled          :
IsReportManagerEnabled           : True
IsSharePointIntegrated           : False
IsWebServiceEnabled              : True
IsWindowsServiceEnabled          : True
MachineAccountIdentity           : CORP\SCW000002222$
PathName                         : C:\Program Files\Microsoft SQL Server Reporting
                                   Services\SSRS\ReportServer\rsreportserver.config
SecureConnectionLevel            : 0
SenderEmailAddress               :
SendUserName                     :
SendUsingSMTPServer              : True
ServiceName                      : SQLServerReportingServices
SMTPAuthenticate                 : 0
SMTPServer                       :
SMTPUseSSL                       : False
UnattendedExecutionAccount       :
Version                          : 14.0.600.490
VirtualDirectoryReportManager    :
VirtualDirectoryReportServer     :
WindowsServiceIdentityActual     : NT SERVICE\SQLServerReportingServices
WindowsServiceIdentityConfigured : NT SERVICE\SQLServerReportingServices
PSComputerName                   : SCW000002222

**Comment by ClaudioESSilva** [comment]
Good.

So use this two parameters together` -ReportServerInstance "SSRS" -ReportServerVersion SQLServer2017`

**Comment by HealisticEngineer** [comment]
Got a database credential error but quickly solved that with adding the -DatabaseCredential

so it seem to work now, the final syntx is:
Set-RsDatabase -DatabaseServerName Myserver\myinstance -Name reportingdb_name -DatabaseCredentialType Windows -ReportServerInstance "SSRS" -ReportServerVersion SQLServer2017 -DatabaseCredential domain\user

**Comment by parthsha** [comment]
Thanks @ClaudioESSilva for promptly resolving this issue. I will close it now.
