### ISSUE TITLE
Attempting to copy reports and datasources from local files to reports server fails on data source.

### ISSUE THREAD

**Issue by propellor** [Microsoft/ReportingServicesTools#11]
I have a folder with two reports and a shared data source in it's own subfolder.  I have exported the files to local disk using Out-RsFolderContent.  When using Write-RsFolderContent to copy the files to another report server, the following error occurs:

Exception calling "CreateCatalogItem" with "7" argument(s): "The value of parameter 'Definition' is not valid. ---> Microsoft.ReportingServices.Diagnostics.Utilities.InvalidParameterException: The value of parameter 'Definition' is not 
valid. ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 2, position 1."
At C:\...\ReportingServicesTools\Functions\CatalogItems\Write-RsCatalogItem.ps1:108 char:5
+     $Proxy.CreateCatalogItem($itemType, $itemName, $Destination, $ove ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SoapException 

SSRS 2012
Windows 7 
PS Version 5.0.10586.117       

Thanks!!!

**Comment by jtarquino** [comment]
Seems to be a duplicated from the one reported by @sqlchicken  see issue #9 , if you have a fix in mind please send a pull request.

Thanks
