### ISSUE TITLE
`Write-RsRestFolderContent` does not pass $Credential and $Overwrite to `Write-RsRestCatalogItem`

### ISSUE THREAD

**Issue by skfd** [Microsoft/ReportingServicesTools#113]
It's three bugs in `Write-RsRestFolderContent`:
* `Write-RsRestFolderContent` does not pass $Credential `Write-RsRestCatalogItem`.
* `Write-RsRestFolderContent` does not pass $Overwrite `Write-RsRestCatalogItem`.
* `Write-RsRestCatalogItem` Requires RestApiVersion to be explicitly set to 'v1.0'. If `RestApiVersion` is not set, it will crash.

Here's how I ran this script:

```ps1
$params =  @{
    Path = 'C:\PowerBI'
    RsFolder = '/'
    ReportPortalUri = 'http://example.com/PBIReports'
    Credential = (Get-Credential -UserName "skfd" -Message "your password sir")
    RestApiVersion = 'v1.0' # note: this is a workaround
}

if ($VerbosePreference -ne 'SilentlyContinue') {
    $params.Add('Verbose', $null)
}

Write-RsRestFolderContent @params
```

Powershell version: `5.1.16299.15`
Script version: `0.0.3.3`

**Comment by parthsha** [comment]
1) and 2) are bugs. They should be fixed.

As for 3), RestApiVersion v1.0 is for SQL Server Reporting Services 2016 users only. For SQL Server Reporting Services 2017 and Power BI Report Server users, there is a v2.0 for REST API, which is supported by Microsoft (unlike v1.0).

**Comment by skfd** [comment]
Thank you for verifying the issues!

> For SQL Server Reporting Services 2017 and Power BI Report Server users, there is a v2.0

I see that [repo has branching](https://github.com/Microsoft/ReportingServicesTools/blob/603fd005ee79bbb0c33b0ca9dddca4e323b92e51/ReportingServicesTools/Functions/CatalogItems/Rest/Write-RsRestCatalogItem.ps1#L100-L107) for version one and two. Powershell Gallery version still has this issue, will use code from github, it's cool!
