### ISSUE TITLE
Question\feature request: can I set Datasource of the Power BI report?

### ISSUE THREAD

**Issue by skfd** [Microsoft/ReportingServicesTools#116]
My Power BI files are targeted unto my local SSAS server when I publish them. After that I have to re-target Data Sources in each report to production SSAS server. Would love to automate this task using this tool.

I'm trying use `/PowerBIReports({Id})/DataSources` directly, but [swagger docs](https://app.swaggerhub.com/apis/microsoft-rs/PBIRS/2.0#/PowerBIReports/UpdatePowerBIReportDataSource) are confusing.

I think this is a common use case. What do you think?

**Comment by parthsha** [comment]
I have a sample that will show you how to do this, however I won't have my blog post ready until next week (mostly due to Thanksgiving break). It should be up by latest Tuesday (November 29th). Is that okay with you?

**Comment by skfd** [comment]
Looking forward to that! I'm stuck at building proper payload.

**Comment by parthsha** [comment]
There was a lot of content to cover but I hope this blog post will answer all your questions: https://parthpsha.com/programmatically-setting-and-verifying-data-source-credentials-for-power-bi-reports/. If something is unclear, can you please leave a comment on the blog post instead of here? Thanks!

**Comment by skfd** [comment]
Thank you for the blog post, I have advanced further in my understanding. Unfortunatly I still can not change datasource\credentials for PowerBI+SSAS combo. `Model.CheckDataSourceConnection` does not work too. Both return generic 400 error.

```ps1
function check_connection($ReportPortalUri, $name, $datasource_id, $creds) {
    $url = "$ReportPortalUri/api/v2.0/PowerBIReports(Path='/$name')/Model.CheckDataSourceConnection"

    $ok = Invoke-WebRequest `
        -Uri $url `
        -Method Post `
        -ContentType "application/json" `
        -Body (ConvertTo-Json @{ DataSourceName = $datasource_id }) `
        -Credential $creds

    $ok
}

function set_dataset($ReportPortalUri, $name, $Creds) {
    $url = "$ReportPortalUri/api/v2.0/PowerBIReports(Path='/$name')/DataSources"

    $data_sources = Invoke-WebRequest `
        -Uri $url `
        -Method Get `
        -ContentType "application/json" `
        -Credential $creds | ConvertFrom-Json

    $data_source = $data_sources.value | select -First 1

    $data_source.ConnectionString = "Data Source=example.local\northwind;Initial Catalog=NorthwindTabular;Cube=Model"

    #TODO: how to change under whom the reports are run?
    #$data_source.DataModelDataSource.AuthType = "Windows"
    #$data_source.DataModelDataSource.Username = "domain\user"
    #$data_source.DataModelDataSource.Secret = "plaintextpassword?"

    [array]$payload_obj = @($data_source)

    $payload = ConvertTo-Json -InputObject $payload_obj

    Invoke-WebRequest `
        -Uri $url `
        -Method Patch `
        -Body $payload `
        -ContentType "application/json" `
        -Credential $creds
}
```

**Comment by parthsha** [comment]
You can't change connection string of Power BI Report Data Sources. The only thing you can change is AuthType, Username and Secret.

**Comment by skfd** [comment]
Hmm, my deployment scenario was mirroring the one I had with RDL reports.
* I upload PowerBi reports
* I change datasources to point to production SSAS model.

Looks like I have to do it in files themselves, before publishing?

Thanks for help!

**Comment by parthsha** [comment]
Yea for Power BI Reports if you want to modify the connection string, you will have to do it in the Report itself.

**Comment by skfd** [comment]
Thanks, will do it that way!

**Comment by skfd** [comment]
@parthsha do you have any tutorial on editing contents of `pbix` archive? When I do unzip-zip on report it's considered corrupt by PowerBi Server On-Premise. Even though PowerBi Desktop opens it without problem.

**Comment by jtarquino** [comment]
The only supported way to modify pbix files is using Power BI Destkop

**Comment by skfd** [comment]
That's understandable, but I need automation. I think the problem was with encoding that powershell prefers. Here's the snipped that worked for me.

```ps1
function Update-PowerBiConnectionString($file, $connectionString) {
    $item = Copy-Item $file temp.zip

    Expand-Archive temp.zip
    
    $con = Get-Content -Raw -Path ".\temp\Connections" | ConvertFrom-Json
    $con.Connections[0].ConnectionString = $connectionString
    [System.IO.File]::WriteAllLines(".\temp\Connections", ($con | ConvertTo-Json -Depth 20 -Compress))

    Compress-Archive temp/* -DestinationPath temp.zip -Update
    
    Remove-Item $file -Force
    Move-Item temp.zip $file -Force
    
    Remove-Item temp -Recurse -Force
}

Update-PowerBiConnectionString '.\powerbi\Operational Dashboard.pbix' 'Data Source=NORTHWIND02\SALES;Initial Catalog=NorthWindTabular;Cube="Sales Dashboard"'
```
