### ISSUE TITLE
Set-RsUrlReservation fails with error code -2147220930

### ISSUE THREAD

**Issue by mscott83** [Microsoft/ReportingServicesTools#121]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm trying to change my Report Server URL to a different URL using Set-RsUrlReservation. It fails with the error "Failed to reserve Urls Failed Setting Virtual Directory for ReportServerWebService, Errocode: -2147220930"

I can manually change the URL to the desired state using the RS Configuration Manager GUI, but the PowerShell CmdLet fails - so I'm reasonably confident it's not permissions or anything like that.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Run the following command to change the Report Service:

Set-RsUrlReservation -ReportServerVirtualDirectory "Reports" -PortalVirtualDirectory "ReportServer" -ListeningPort 8080 -Verbose 

**What is the expected behavior?**

Report Server URL is changed to the desired virtual directory and port.

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

This is on Windows Server 2016, with SQL Server 2016 Developer Edition. PSVersion:

Name                           Value
----                           -----
PSVersion                      5.1.14393.1884
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1884
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Using version 0.3.3 of the ReportingServicesTools module

**Comment by mscott83** [comment]
As a further test, simply running "Set-RsUrlReservation" with no parameters, which should set the default virtual directory and port settings, also fails with the same error.

**Comment by parthsha** [comment]
@mscott83 there is a known bug in Set-RsUrlReservation where if you already had a previous URL reservation, then it will fail to reserve the new URLs. From what you are saying, it seems like you didn't have any URLs and you ran this command to do the first reservation. Is that correct?

**Comment by mscott83** [comment]
I did have a URL reservation, but it was the default one set by a vanilla installation (http://+:80/Reports and http://+:80/ReportServer). 

So yes I may be hitting this bug.

**Comment by jtarquino** [comment]
The command in its current form is intended for installations with no existing configuration, we welcome community contributions feel free to send a PR to improve the command to validate if the url is already registered before it executes
