### ISSUE TITLE
Add support for KPIs

### ISSUE THREAD

**Issue by martkopecky** [Microsoft/ReportingServicesTools#123]
I would like to propose a feature request: add support for KPIs
in CatalogItems functions

Currently, it is impossible to setup automatic download/upload for this type of objects.

**Comment by parthsha** [comment]
Have you tried using Write-RsRestCatalogItem and Out-RsRestCatalogItem. I believe these commands can download and upload KPIs.

**Comment by parthsha** [comment]
@martkopecky I was wondering if you had any issues with any of the suggest commands above. I will close this issue for now. If you had any issues, please feel free to re-open this issue.
