### ISSUE TITLE
Set-RsDatabase - -IsExistingDatabase parameter is not working as expected

### ISSUE THREAD

**Issue by gorkam23** [Microsoft/ReportingServicesTools#127]
Bug - 

When I used the -IsExistingDatabase parameter with Set-RsDatabase, I was unable to use the SSRS site afterwards.

Only when I had the cmdlet create a new ReportServer database did everything work as expected.

Using Powershell 5.x with 0.0.3.3 RSTools on SQL 2016 with SSRS 2016.

Thanks!

**Comment by parthsha** [comment]
Hi @gorkam23! Just so that I understand the issue correctly, you specified -IsExistingDatabase because you wanted SSRS to use an existing ReportServer database. Is that correct?

**Comment by gorkam23** [comment]
Ok, now it's working.  I was writing up documentation to recreate the issue and it did not happen this time!  I'll reopen the case if it does happen again.  

Sorry for the confusion!

Merry Christmas all!
