### ISSUE TITLE
Set-RsURLReservation

### ISSUE THREAD

**Issue by gorkam23** [Microsoft/ReportingServicesTools#129]
Question here - 

I was experimenting with this to configure new URLs for a new SSRS instance. 

SSRS 2017
Powershell 5.x

I seem to have problems with the ReportServerInstance parameter.

Please see my attached image.  The instance name is MSSQLSERVER\SSRS  

I tried both MSSQLSERVER\SSRS and just SSRS for the ReportServerInstance parameter, also in quotes and not in quotes.

I am also attaching the output from SSRS Configuration Manager. 

I'm sure I am just missing something obvious.  Happy to update the Examples for this command after *I* understand it...  

Thanks, Mike

![image](https://user-images.githubusercontent.com/32223642/34504994-213544f0-efd7-11e7-95fc-68c86e57a5fe.png)

![image](https://user-images.githubusercontent.com/32223642/34505098-c4ad92c2-efd7-11e7-996d-1afed093d217.png)

**Comment by jtarquino** [comment]
You might need to pass also the -ReportServerVersion 14 (I think it also works -ReportServerVersion SQLServer2017) as the default is for 13 (SSRS 2016)

**Comment by gorkam23** [comment]
Yes, that is the trick.  When I put in -ReportServerVersion SQLSERVER2017 it worked just fine.  

RTFM!!!  I would like to update the example text though so other people don't run into this issue if possible.  How do I do that?

**Comment by jtarquino** [comment]
Just sent a Pull Request with the change to the file https://github.com/Microsoft/ReportingServicesTools/blob/master/ReportingServicesTools/Functions/Admin/Set-PbiRsUrlReservation.ps1

**Comment by gorkam23** [comment]
Sorry, I am confused.  Can I submit an updated example then?

**Comment by jtarquino** [comment]
Yes you can, if you aren't familiar with contributions in GitHubs you might want to start with 
https://help.github.com/articles/creating-a-pull-request/
Typically those are created from your own fork of the repository https://help.github.com/articles/about-forks/
