### ISSUE TITLE
Register-PowerBI - Question

### ISSUE THREAD

**Issue by gorkam23** [Microsoft/ReportingServicesTools#130]
Question about parameter:  -AppObjectID

Any suggestions what I can put here?  

Thanks!

Mike

**Comment by jtarquino** [comment]
There are more details available here https://blogs.msdn.microsoft.com/sqlrsteamblog/2016/07/22/manually-configuring-power-bi-integration-in-reporting-services/
You get tha value from the application manifest in the Azure AD portal
