### ISSUE TITLE
Update-RsSubscription doesnt exist

### ISSUE THREAD

**Issue by cporteou** [Microsoft/ReportingServicesTools#131]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Function listed in Readme.md doesnt exist
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

**Comment by jtarquino** [comment]
It was renamed on change #125 to Set-RsSubscription, I'll update the readme.md

**Comment by cporteou** [comment]
Perfect. That will work for only updating creds? I wasn't having much luck. I'll get back into it. Cheers
