### ISSUE TITLE
Initialize-RS - what is the purpose of it?

### ISSUE THREAD

**Issue by gorkam23** [Microsoft/ReportingServicesTools#132]
Question about command

SSRS 2016/2017, Powershell 5.x

As far as I know, you need to do the following to set up SSRS:

Install the application
Set-RsDatabase to setup the reporting Server database
Set-RsUrlReservation to configure the Web Portal URL and the Web Services URL

After that and a restart you are done.

What is Initialize used for?

Thanks!

Mike

**Comment by jtarquino** [comment]
The functions call the same set of WMI apis that the config tool does, the initialization method is documented https://docs.microsoft.com/en-us/sql/reporting-services/wmi-provider-library-reference/configurationsetting-method-initializereportserver
