### ISSUE TITLE
Does this module work with older ReportingServices?

### ISSUE THREAD

**Issue by crshnbrn66** [Microsoft/ReportingServicesTools#14]
Question

It's stated this works with 2016 does it work with earlier versions of Reporting Services?

for what it's worth I've written a fair amount of scripting for Reporting services querying the ASMX pages in this Script: 
https://gist.github.com/crshnbrn66/b10e43ef0dadf7f4eeae620428b2cdd9

**Comment by jtarquino** [comment]
Yes it does, most part of the cmdlets doesn't need version of the server, for those that need it there is a SqlServerVersion parameter

**Comment by crshnbrn66** [comment]
thank you
