### ISSUE TITLE
$item.TypeName should be $item.Type 

### ISSUE THREAD

**Issue by white-bee** [Microsoft/ReportingServicesTools#141]
https://github.com/Microsoft/ReportingServicesTools/blob/034f4b91910fdf7ddb4a99181735f4cbea82cd56/ReportingServicesTools/Functions/CatalogItems/Out-RsFolderContent.ps1#L106

This does not work due to the fact the property name is Type and not TypeName according to the https://msdn.microsoft.com/en-us/library/reportservice2005.catalogitem.type.aspx

**Comment by mika-n** [comment]
Yes it works.  The link you specified is for older RS2005, but newer RS2010 has TypeName property.
https://msdn.microsoft.com/en-us/library/reportservice2010.catalogitem.typename.aspx
