### ISSUE TITLE
Set-RsDatabase with DatabaseCredentialType SQL still seems to try to do integrated authentication 

### ISSUE THREAD

**Issue by deitch** [Microsoft/ReportingServicesTools#144]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Cannot run `Set-RsDatabase` with `-DatabaseCredentialType SQL`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I am running against MSSQL in Docker on Linux. I run the following:

```
PS \> Set-RsDatabase -DatabaseServerName "$sqlserver" -DatabaseName "$sqldb" -DatabaseCredentialType SQL -Confirm:$false -Verbose -ReportServerInstance PBIRS -ReportServerVersion SQLServer2017 -DatabaseCredential $sqlCredentials
```

When I do, I get the following output:

```
VERBOSE: Performing the operation "Configure to use ****** as database, using SQL
authentication" on target "localhost (SQLServer2017) \ PBIRS".
VERBOSE: Generating database creation script...
VERBOSE: Generating database creation script... Complete!
VERBOSE: Executing database creation script...
VERBOSE: Executing database creation script... Failed!
Invoke-Sqlcmd : Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication.
At C:\Program Files\WindowsPowerShell\Modules\ReportingServicesTools\0.0.4.4\Functions\Admin\Set-RsDatabase.ps1:150
char:17
+ ...             Invoke-Sqlcmd -ServerInstance $DatabaseServerName -Query  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlException
    + FullyQualifiedErrorId : SqlExectionError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
```

Logs from the MSSQL server:

```
2018-02-17 20:24:29.43 Logon       Error: 17806, Severity: 20, State: 14.
2018-02-17 20:24:29.43 Logon       SSPI handshake failed with error code 0x80090308, state 14 while establishing a connection with integrated security; the connection has been closed. Reason: AcceptSecurityContext failed. The operating system error code indicates the cause of failure. The token supplied to the function is invalid   [CLIENT: 10.51.248.0]
2018-02-17 20:24:29.43 Logon       Error: 18452, Severity: 14, State: 1.
2018-02-17 20:24:29.43 Logon       Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication. [CLIENT: 10.51.248.0]
```

**What is the expected behavior?**

Login should work

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

PowerBI and Powershell (running locally) on Windows Server 2016. MSSQL Docker image `microsoft/mssql-server-linux:2017-CU3`.

Since I am passing `-DatabaseCredentialType SQL`, should it not be connecting to the database using SQL credentials?

I can confirm the user is set up as a database user:

```
1> select * from sys.server_principals where name = "PBIRS"
2> go
name                                                                                                                             principal_id sid                                                                                                                                                                          type type_desc                                                    is_disabled create_date             modify_date             default_database_name                                                                                                            default_language_name                                                                                                            credential_id owning_principal_id is_fixed_role
-------------------------------------------------------------------------------------------------------------------------------- ------------ ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ---- ------------------------------------------------------------ ----------- ----------------------- ----------------------- -------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- ------------- ------------------- -------------
PBIRS                                                                                                                                     262 0xF98CE53E7EA5434889B0860740E7E622                                                                                                                                           S    SQL_LOGIN                                                              0 2018-02-17 20:09:08.463 2018-02-17 20:09:08.497 master                                                                                                                           us_english                                                                                                                                NULL                NULL             0

(1 rows affected)
1> select * from sys.database_principals where name = 'PBIRS'
2> go
name                                                                                                                             principal_id type type_desc                                                    default_schema_name                                                                                                              create_date             modify_date             owning_principal_id sid                                                                                                                                                                          is_fixed_role authentication_type authentication_type_desc                                     default_language_name                                                                                                            default_language_lcid allow_encrypted_value_modifications
-------------------------------------------------------------------------------------------------------------------------------- ------------ ---- ------------------------------------------------------------ -------------------------------------------------------------------------------------------------------------------------------- ----------------------- ----------------------- ------------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- ------------- ------------------- ------------------------------------------------------------ -------------------------------------------------------------------------------------------------------------------------------- --------------------- -----------------------------------
PBIRS                                                                                                                                       7 S    SQL_USER                                                     dbo                                                                                                                              2018-02-17 20:09:08.487 2018-02-17 20:09:08.487                NULL 0xF98CE53E7EA5434889B0860740E7E622                                                                                                                                                       0                   1 INSTANCE                                                     NULL                                                                                                                                              NULL                                   0

(1 rows affected)
```

As far as I can tell (but might have misunderstood), it doesn't appear to use the credentials passed until **after** trying to create the database and set up the database rights. See [here](https://github.com/Microsoft/ReportingServicesTools/blob/master/ReportingServicesTools/Functions/Admin/Set-RsDatabase.ps1#L150) and [here](https://github.com/Microsoft/ReportingServicesTools/blob/master/ReportingServicesTools/Functions/Admin/Set-RsDatabase.ps1#L181)

Does it not support fully initializing the database?

**Comment by deitch** [comment]
FWIW, this is the first PS interaction with a newly installed PowerBI Report Server. Simply trying to automate its setup in a cloud server: install, configure, it runs.

**Comment by deitch** [comment]
@jtarquino I don't mind helping to debug, but I am lost as to how `Set-RsDatabase` is supposed to work.

> the user is only used in the last call to SetDatabaseConnection

That appears to be [here](https://github.com/Microsoft/ReportingServicesTools/blob/master/ReportingServicesTools/Functions/Admin/Set-RsDatabase.ps1#L194)

But I don't get it. If it is only used there, then how is `Invoke-SqlCmd` called 13 lines earlier [here](https://github.com/Microsoft/ReportingServicesTools/blob/master/ReportingServicesTools/Functions/Admin/Set-RsDatabase.ps1#L181) ? Does it not need those credentials to run `Invoke-SqlCmd`?

It looks like it creates the `$rsWmiObject` [line 105](https://github.com/Microsoft/ReportingServicesTools/blob/master/ReportingServicesTools/Functions/Admin/Set-RsDatabase.ps1#L105) then generates the database creation script from that `$rsWmiObjewct` at [line 134](https://github.com/Microsoft/ReportingServicesTools/blob/master/ReportingServicesTools/Functions/Admin/Set-RsDatabase.ps1#L134), which is all before it actually tries to use the database credentials [line 194](https://github.com/Microsoft/ReportingServicesTools/blob/master/ReportingServicesTools/Functions/Admin/Set-RsDatabase.ps1#L194).

Is it a different set of credentials? 

I am quite confused as to how initial setup of a database is supposed to work. It looks a bit like this script does two things:

1. Create the database and initialize the user rights for the targeted user (the one passed in credentials) using whatever the current account it is running under.
2. Set the PBIRS to connect to the database using that user, which is just lines 191 to the end.

Is that right? If so, how do I use an SQL (not system) admin account to take care of step 1? Is it a different PS call?

**Comment by jtarquino** [comment]
You are describing correctly the workflow, is a two step process where first the database script is generated and applied to the database and then the Report Server is configured to use that database with a particular set of credentials.

The error you are seeing is likely to be caused by the line [150](https://github.com/Microsoft/ReportingServicesTools/blob/a13f474c597bff79d8e544a7fb7da09d4af69372/ReportingServicesTools/Functions/Admin/Set-RsDatabase.ps1#L150) and [181](https://github.com/Microsoft/ReportingServicesTools/blob/a13f474c597bff79d8e544a7fb7da09d4af69372/ReportingServicesTools/Functions/Admin/Set-RsDatabase.ps1#L181)
Seems to be original author assumed the user running the function would have permissions to the database.
The change will require to add username and password when available [Invoke-sqlcmd](https://docs.microsoft.com/en-us/powershell/module/sqlserver/invoke-sqlcmd?view=sqlserver-ps)

Also it opens the question if we want to use the same credentials to configure RS than the credentials used to create the database, probably a new set of parameters should be added to pass the SQL Credentials to create the database (you need to be sysadmin in order to create the database but not to run RS)

**Comment by deitch** [comment]
That does explain the issue. 

So what would be the right way to do this? Assume I cannot use a windows account for any step and must use sql credentials? Is there a way ?

**Comment by jtarquino** [comment]
In my opinion a new set of parameters should be added to allow a user to specify SQL credentials to create the database, basically if they show up those will be used otherwise will just use the current user as is now

**Comment by jtarquino** [comment]
Could be something like  [System.Management.Automation.PSCredential] SQLAdminCredential and document that is used to create the database and then before inkoke-sqlcmd is called verify if that SQLAdminCredential is not null to use it

**Comment by deitch** [comment]
Makes sense. I’ll see if it’s doable.

**Comment by deitch** [comment]
@jtarquino take a look at #146
