### ISSUE TITLE
New-RsFolder Description

### ISSUE THREAD

**Issue by themakokid** [Microsoft/ReportingServicesTools#145]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The property value for new-rsfolder is set to $null. Adding descriptions would be useful.

**Comment by jtarquino** [comment]
Sounds like a great improvement, I would like to invite you to send a pull request with the modification

**Comment by crunchyguy** [comment]
In attempting to do this, I'm running into the following issue:

> New-RsWebServiceProxyHelper : The term 'New-RsWebServiceProxyHelper' is not recognized as the name of a cmdlet

I'm unable to find any reference to this cmdlet anywhere.

**Comment by jtarquino** [comment]
Did you check the instructions for local development under [Local Testing and Development](https://github.com/Microsoft/ReportingServicesTools#local-testing-and-development)

**Comment by crunchyguy** [comment]
I'm failing miserably at getting things to work in my favor. This is the code I've been using to add descriptions using the API.

`    $Proxy = New-WebServiceProxy -Uri $RSUri -UseDefaultCredential
    $type = $Proxy.GetType().Namespace
    $datatype = ($type + '.Property')
    $property = New-Object ($datatype);
    $property.Name = "Description"
    $property.Value = $Description
    $Proxy.CreateFolder($name, $path, $property)`

**Comment by jzabroski** [comment]
Hi cruncyguy,
I think either you pasted the code incorrectly or you simply need to use some the ENTER key and you are all set.

**Comment by crunchyguy** [comment]
It doesn't format correctly with line breaks

**Comment by joshcorr** [comment]
Noticed this issue was a little stale, so I submitted a PR with some code based off of another cmdlet in this module with a Description parameter.
