### ISSUE TITLE
Recurse use

### ISSUE THREAD

**Issue by SMSSWS** [Microsoft/ReportingServicesTools#153]
**Do you want to request a *feature* or report a *bug*?**
Bug?
**What is the current behavior?**
Using ReportingServicesTools ver 0.0.0.4 module from PSGallery. Everytime I use -Recurse I get errors 

**Without -Recurse** 
PS C:\> Get-RsCatalogItemRole -Identity 'XXXXXX'  -path '/'

Identity       : XXXXXX
Path           : /
TypeName       : Folder
Roles          : {Browser, Content Manager, My Reports, Publisher...}
ParentSecurity : False

**Without -Recurse**
PS C:\> Get-RsCatalogItemRole -Identity 'XXXXXX'  -path '/DataSources'

Identity       : XXXXXX
Path           : /DataSources
TypeName       : Folder
Roles          : {Browser, Content Manager, My Reports, Publisher...}
ParentSecurity : False

**With -Recurse**
PS C:\> Get-RsCatalogItemRole -Identity XXXXXX'  -path '/DataSources' -recurse
Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.
At C:\Program Files\WindowsPowerShell\Modules\reportingservicestools\0.0.4.4\Functions\Security\Get-RsCatalogItemRole.ps1:136 char:21
+ ...             $catalogItemRoles +=  New-RsCatalogItemRoleObject -Policy ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Identity       :XXXXXX
Path           : /DataSources
TypeName       : Folder
Roles          : {Browser, Content Manager, My Reports, Publisher...}
ParentSecurity : False

.
.

It seems like it should just work, but various uses seem to give this error. Also it only shows 4 out of 5 assigned roles - is there a way to get at the entirety. I'm new to using PS and these tools.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
PS C:\> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.0.10240.17443
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   10.0.10011.16384
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3

Using against a 2017 local RS and 2016 Remote RS same effect.

Also, see the following:
PS C:\> Install-Module -Name Pester
WARNING: Version '3.3.5' of module 'Pester' is already installed at 'C:\Program Files\WindowsPowerShell\Modules\Pester\3.3.5'. To delete version '3.3.5'
and install version '4.3.1', run Install-Module, and add the -Force parameter.
PS C:\>

This does work(3/5/18 updated):  
Get-RsCatalogItemRole -ReportServerUri 'http://YYYYYY/reportserver' -Path '/' -Recurse

**Comment by ClaudioESSilva** [comment]
Hi @SMSSWS I have fixed this on PR #174 . Can you get my branch from here: https://github.com/ClaudioESSilva/ReportingServicesTools/tree/FixGet-RsCatalogItemRole-Recurse and test it?
Thanks!

**Comment by SMSSWS** [comment]
Will give it a try ASAP. Finishing up a project deadline for May. Thanks for attending to this bug item.
