### ISSUE TITLE
Write-RsRestFolderContent should skip attempting to create folders that already exist (especially if -Recurse and/or -Overwrite is used)

### ISSUE THREAD

**Issue by wsuhoey** [Microsoft/ReportingServicesTools#157]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Line 136 of `Write-RsRestFolderContent` does `New-RsRestFolder` without checking the existence of the folder on target first:

```New-RsRestFolder -WebSession $WebSession -RestApiVersion $RestApiVersion -FolderName $item.Name -RsFolder $parentFolder | Out-Null```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

```
$tempFolder = "C:\temp\SSRS\"\

# ($tempfolder is a local drive where the content is downloaded from source server via Out-RsFolderContent)

# get content from source
Out-RsFolderContent -Proxy $SourceProxy -RsFolder $RsFolder -Destination $tempFolder -Recurse

# upload content from temp folder
Write-RsRestFolderContent -WebSession $DestSessionRest -RestApiVersion v2.0 -RsFolder $RsFolder -Path $tempfolder -ReportPortalUri $DestUriRest -Recurse -Overwrite
```

**What is the expected behavior?**
Since `-Recurse` and `-Overwrite` flags are used in my repro, we shouldn't be getting halting / terminating errors from Write-RsRestFolderContent (which calls New-RsRestFolder on line 136) about folder(s) already existing on the target.

It should continue placing folder content if the target folder already exists, instead of breaking and stopping.

Without this, as a workaround we are forced to delete target folders prior to migrating reports from one SSRS server to another SSRS server if it has been already migrated once previously. Furthermore, deleting target folders would erase any security permissions applied to that folder, further causing more pain to re-apply security later.

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
5.1.15.063.786
0.0.4.6 ReportingServicesTools
Unknown if this worked in previous script versions.

**Comment by wsuhoey** [comment]
Hi @ClaudioESSilva ,<br>

I'm still receiving an error using my same repro steps, even though I have `-Overwrite`.<br>
I think `New-RsRestFolder` might need to be modified too?<br><br>
I loaded the module using `-Force` after copy/pasting and overwriting the original files with yours.
The error I'm getting is like this:<br><br>

`Failed to create folder 'folder2' in '/folder1': The remote server returned an error: (409) Conflict.`<br>
`At C:\Program Files\WindowsPowerShell\Modules\ReportingServicesTools\0.0.4.6\Functions\CatalogItems\Rest\New-RsRestFolder.ps1:106 char:13`<br>
`+             throw (New-Object System.Exception("Failed to create fold …`<br>
`+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`<br>
`    + CategoryInfo          : OperationStopped: (:) [], Exception`<br>
`    + FullyQualifiedErrorId : Failed to create folder 'folder2' in '/folder1': The remote server returned an error: (409) Conflict.`<br><br>

The SSRS directory structure for this failure is like this:<br>
/folder1/folder2/.<br>
So it's failing on the folder within a folder.

**Comment by ClaudioESSilva** [comment]
Hi @wsuhoey ,
You are right, don't know how but the branch just have 1 of 4 changes I mage.

Please get the code from the original PR: https://github.com/Microsoft/ReportingServicesTools/pull/173/files
and try again.

Using this PR:
![image](https://user-images.githubusercontent.com/19521315/40707291-2f6d9466-63e8-11e8-85e4-65d0b567868a.png)

Thank you!

**Comment by RoyLofthus** [comment]
I have the same problem using v0.0,47 with subfolders. 
Will the fix in PR172 be merged with master?
