### ISSUE TITLE
Restore-RsEncryptionKey failing on 2017 due to service name assumption

### ISSUE THREAD

**Issue by JoDouglass** [microsoft/ReportingServicesTools#159]
**Do you want to request a feature or report a bug?**
Bug.

**What is the current behavior?**
I am getting this error when using Restore-RsEncryptionKey on RS 2017:
> Failed to restart Report Server database service. Manually restart it for the change to take effect! Cannot find any service with service name 'ReportServer$SSRS '.

It seems like the function is restoring the encryption key, but then failing to stop and restart the service afterwards.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
You need a reporting services 2017 installation. Back up the encryption key to a drive.

I am calling the function like this:
```
Restore-RsEncryptionKey -ComputerName MyName -ReportServerVersion SQLServer2017 -ReportServerInstance SSRS -Password 'MyPass' -KeyPath 'C:\MyFolder\MyKeyFile.snk'
```

When working with 2017, the instance name must be passed in or an error is instead received in relation to the WMI namespace. SSRS is actually the default instance in 2017.

The problem is that the function presumes that the reporting server service is called ReportServer, and that if a different instance name is passed in, the service will instead be ReportServer$InstanceName. 

However, ReportServer is the name of the pre-2017 service. In 2017 it seems to be called SQLServerReportingServices.

Here is the code that's causing the problem:
```
        $reportServerService = 'ReportServer'
        
        if ($rsWmiObject.InstanceName -ne "MSSQLSERVER")
        {
            if($rsWmiObject.InstanceName -eq "PBIRS")
            {
                $reportServerService = 'PowerBIReportServer'
            }
            else
            {
                $reportServerService = $reportServerService + '$' + $rsWmiObject.InstanceName
            }
        }
```

**What is the expected behavior?**
The function should restore the encryption key, then stop and restart the reporting services service, which in 2017 is called SQLServerReportingServices.

SSRS is the default instance name on 2017, so perhaps a check could be added to set `$reportServerService` to SQLServerReportingServices if the instance name is SSRS, similar to how PBIRS and PowerBIReportServer is done currently?

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
I don't believe this issue is affected by PoSh, OS, or module version. The only problem is the function not supporting Reporting Services 2017. The function works fine with RS 2016 and earlier.

**Comment by jtarquino** [comment]
Thanks for reporting the issue, I would like to invite you to clone the repo and contribute with a fix

**Comment by robertoandrade** [comment]
One could also use `-ReportServerVersion` value to determine if it should change the service name to the new one (ie: `SQLServer2017` or `14` which apparently are valid values)
