### ISSUE TITLE
Set-RsDatabaseCredentials - invoke-sqlcmd Queries are Timing out.

### ISSUE THREAD

**Issue by washerk** [Microsoft/ReportingServicesTools#162]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**

Using Admin Function "Set-RSDatabaseCredentials", when reaching #Step2 - Run Database Rights script,
long running query results in a timeout.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

To be able to specify\pass in QueryTimeout Value, so that long running queries do not fail when running Set-RsDatabaseCredentials

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
PSVersion                      5.0.10586.117 
Microsoft Windows [Version 6.3.9600]

**Comment by jtarquino** [comment]
I would like to invite you to contribute with the change to the module to add the feature

**Comment by washerk** [comment]
Thanks jtarquinio, will do!
