### ISSUE TITLE
Is the file appveyor.yml compatible with SQL Server 2016 Enterprise 64bit?

### ISSUE THREAD

**Issue by ssicefox** [Microsoft/ReportingServicesTools#163]
Hi,

I just discover that you used SQLServer2017 in the appveyor.yml.

But I installed SQL Server2016 Enterprise 64bit, so I don't know if the appveyor.yml is compatible with SQL Server2016. If yes, please tell me how I should do.

Best regards.
Wei

**Comment by jtarquino** [comment]
We keep the integration tests with the latest version, you could use any version you need when using the functions
