### ISSUE TITLE
The new error message

### ISSUE THREAD

**Issue by ssicefox** [Microsoft/ReportingServicesTools#164]
PS C:\Windows\system32> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
PS C:\Windows\system32> Invoke-Expression (Invoke-WebRequest https://raw.githubusercontent.com/Microsoft/ReportingServic
esTools/master/Install.ps1)
Deleting previously installed module...
Downloading archive from ReportingServiceTools GitHub...
Unzipping archive...
ReportingServicesTools has been successfully downloaded to C:\Users\Wei LI\Documents\WindowsPowerShell\Modules\ReportingServicesTools!
Cleaning up...
Importing ReportingServicesTools Module...
Import-Module : File C:\Users\Wei
LI\Documents\WindowsPowerShell\Modules\ReportingServicesTools\ReportingServicesTools\ReportingServicesTools.psm1
cannot be loaded. The file C:\Users\Wei
LI\Documents\WindowsPowerShell\Modules\ReportingServicesTools\ReportingServicesTools\ReportingServicesTools.psm1 is
not digitally signed. You cannot run this script on the current system. For more information about running scripts and
setting execution policy, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:102 char:1
+ Import-Module "$path\ReportingServicesTools\ReportingServicesTools.ps ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [Import-Module], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by jtarquino** [comment]
Check your execution policy (the command is set-executionpolicy)
