### ISSUE TITLE
How to use ReportingServicesTools's command after installing it?

### ISSUE THREAD

**Issue by ssicefox** [Microsoft/ReportingServicesTools#165]
Hi,

With you advice, I installed ReportingServicesTools via Power Shell, but I don't know how to use it.

Do you have a document?

Sorry, I am new for using PowerShell.

Best regards.

**Comment by jtarquino** [comment]
Checkout the list of commands https://github.com/Microsoft/ReportingServicesTools/issues/165 , you can use Get-Help and the name of the command
