### ISSUE TITLE
Get-Help Set-RsDataSource

### ISSUE THREAD

**Issue by ssicefox** [Microsoft/ReportingServicesTools#166]
Hi, 

I used Get-Help Set-RsDataSource, but there is not syntax to show.

PS C:\Windows\system32> Get-Help Set-RsDataSource

Name                              Category  Module                    Synopsis
----                              --------  ------                    --------
Set-RsDataSource                  Function  ReportingServicesTools    ...
Set-RsDataSourcePassword          Function  ReportingServicesTools    ...
Set-RsDataSourceReference         Function  ReportingServicesTools    ...

Best regards.

**Comment by jtarquino** [comment]
Get-Help Set-RsDataSource -detailed, for the full documentation, also I would like to recommend to read some blogs about it like https://sqlvariant.com/2016/11/powershell-for-ssrs-is-here/
