### ISSUE TITLE
Get-Help -detailed name of command

### ISSUE THREAD

**Issue by ssicefox** [Microsoft/ReportingServicesTools#168]
Hi,

I use Get-Help -detailed name of command, but I have nothing.

PS C:\Windows\system32> get-help -detailed Set-RsDataSource

Name                              Category  Module                    Synopsis
----                              --------  ------                    --------
Set-RsDataSource                  Function  ReportingServicesTools    ...
Set-RsDataSourcePassword          Function  ReportingServicesTools    ...
Set-RsDataSourceReference         Function  ReportingServicesTools    ...
PS C:\Windows\system32> get-help -detailed Set-RsDataSet
Name                              Category  Module                    Synopsis
----                              --------  ------                    --------
Set-RsDataSetReference            Function  ReportingServicesTools    ...

Best regards.

**Comment by jtarquino** [comment]
For example
PS C:\WINDOWS\system32> get-help -detailed Set-RsDataSource

NAME
    Set-RsDataSource

SYNOPSIS
    This script updates information about a data source on Report Server.


SYNTAX
    Set-RsDataSource [-RsItem] <String> [-DataSourceDefinition] <Object> [[-Description] <String>] [[-ReportServerUri]
    <String>] [[-Credential] <PSCredential>] [[-Proxy] <Object>] [<CommonParameters>]


DESCRIPTION
    This script updates information about a data source on Report Server that was retrieved using Get-RsDataSource.


PARAMETERS
    -RsItem <String>
        Specify the path to the data source.

    -DataSourceDefinition <Object>
        Specify the data source definition of the Data Source to update

    -Description <String>
        Specify the updated description to display for the data source.

    -ReportServerUri <String>
        Specify the Report Server URL to your SQL Server Reporting Services Instance.
        Use the "Connect-RsReportServer" function to set/update a default value.

    -Credential <PSCredential>
        Specify the credentials to use when connecting to the Report Server.
        Use the "Connect-RsReportServer" function to set/update a default value.

    -Proxy <Object>
        Report server proxy to use.
        Use "New-RsWebServiceProxy" to generate a proxy object for reuse.
        Useful when repeatedly having to connect to multiple different Report Server.

    <CommonParameters>
        This cmdlet supports the common parameters: Verbose, Debug,
        ErrorAction, ErrorVariable, WarningAction, WarningVariable,
        OutBuffer, PipelineVariable, and OutVariable. For more information, see
        about_CommonParameters (https:/go.microsoft.com/fwlink/?LinkID=113216).

    -------------------------- EXAMPLE 1 --------------------------

    PS C:\>Set-RsDataSource -RsItem '/path/to/my/datasource' -DataSourceDefinition $dataSourceDefinition

    Description
    -----------
    This command will establish a connection to the Report Server located at http://localhost/reportserver using
    current user's credentials and update the details of data source found at '/path/to/my/datasource'.




    -------------------------- EXAMPLE 2 --------------------------

    PS C:\>Set-RsDataSource -ReportServerUri 'http://remote-machine:8080/reportserver_sql16' -RsItem
    '/path/to/my/datasource' -DataSourceDefinition $dataSourceDefinition

    Description
    -----------
    This command will establish a connection to the Report Server located at
    http://remote-machine:8080/reportserver_sql16 using current user's credentials and update the details of data
    source found at '/path/to/my/datasource'.




    -------------------------- EXAMPLE 3 --------------------------

    PS C:\>$rsProxy = New-RsWebServiceProxy (...)

    Set-RsDataSource -Proxy $rsProxy -RsItem '/path/to/my/datasource' -DataSourceDefinition $dataSourceDefinition
    Description
    -----------
    This command will establish a connection to the Report Server located at $rsProxy using current user's credentials
    and update the details of data source found at '/path/to/my/datasource'.




REMARKS
    To see the examples, type: "get-help Set-RsDataSource -examples".
    For more information, type: "get-help Set-RsDataSource -detailed".
    For technical information, type: "get-help Set-RsDataSource -full".
