### ISSUE TITLE
Add Description parameter to Write-RsCatalogItem

### ISSUE THREAD

**Issue by davesbrown** [Microsoft/ReportingServicesTools#171]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
No Description parameter in Write-RsCatalogItem

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

I suppose adding similar code that is in New-RsDataSource:

    $additionalProperties = New-Object System.Collections.Generic.List[$propertyDataType]
    if ($Description)
    {
        $descriptionProperty = New-Object $propertyDataType
        $descriptionProperty.Name = 'Description'
        $descriptionProperty.Value = $Description
        $additionalProperties.Add($descriptionProperty)
    }

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

**Comment by ClaudioESSilva** [comment]
Hi @davesbrown ,
I have implemented this on my PR #175.
Can you get my branch from here: https://github.com/ClaudioESSilva/ReportingServicesTools/tree/NewFeaturesWrite-Rs_CatalogItem and test it?

If ok, @jtarquino can merge and close this issue.
Thanks.

**Comment by davesbrown** [comment]
I'm not sure I am testing correctly.  I've downloaded your branch, but I think it is conflicting with the current 'master' branch I have installed.  It does seem to recognize the -Description parameter on tab completion but fails when executing : A parameter cannot be found that matches parameter name 'Description'  But I believe this to be bad install and/or conflict.

**Comment by ClaudioESSilva** [comment]
You need to run 
`Import-Module <your path to my branch\ReportingServicesTools\ReportingServicesTools.psd1 -Force` in order to load the correct module version.
Let me know if not working.

**Comment by davesbrown** [comment]
Excellente, after some trial and error and proper git manipulation, I finally got git to use your branch and passes my testing.  Thank you!

**Comment by ClaudioESSilva** [comment]
yehh! 
thank you! 😄

**Comment by ClaudioESSilva** [comment]
@jtarquino I think you can close this issue. 
Thanks! 👍
