### ISSUE TITLE
The remaining items in the Path Parameter array are not processed by Write-RSRestCatalogItem after a report that already exists is uploaded to the Report Web Portal.

### ISSUE THREAD

**Issue by aeknutson** [Microsoft/ReportingServicesTools#189]
Here’s an example of my call to Write-RSRestCatalogItem.

$ArrayString = @(".\NCC1701.rdl", ".\NCC1864.rdl", ".\NX74205.rdl") 
Write-RsRestCatalogItem -ReportPortalUri 'http://slqserver-16/Reports' -Path $ArrayString -RsFolder '/Kirk' -RestApiVersion 'v1.0' -Overwrite 'true' -Description 'Khan!' 

When the logic falls into the exception handing, it checks for a 409 server error code (the Report already exists in the Report Web Portal) and the Overwrite Switch.  If these conditions exist, the logic attempts the Invoke-WebRequest again with the Item ID.   The retry works successfully, but it exits out of the foreach ($item in $Path) loop and  doesn’t upload the remaining reports in $ArrayString.

catch
            {
                if ($_.Exception.Response -ne $null -and $_.Exception.Response.StatusCode -eq 409 -and $Overwrite)
                {
                    try
                    {
                        Write-Verbose "$itemName already exists at $RsFolder. Retrieving id in order to overwrite it..."
                        $uri = [String]::Format($catalogItemsByPathApi, $itemPath)
                        if ($Credential -ne $null)
                        {
                            $response = Invoke-WebRequest -Uri $uri -Method Get -WebSession $WebSession -Credential $Credential -Verbose:$false
                        }
                        else
                        {
                            $response = Invoke-WebRequest -Uri $uri -Method Get -WebSession $WebSession -UseDefaultCredentials -Verbose:$false
                        }

                        # parsing response to get Id
                        $itemInfo = ConvertFrom-Json $response.Content
                        $itemId = $itemInfo.Id

                        Write-Verbose "Overwriting $itemName at $itemPath..."
                        $uri = [String]::Format($catalogItemsUpdateUri, $itemId)
                        if ($Credential -ne $null)
                        {
                            Invoke-WebRequest -Uri $uri -Method Put -WebSession $WebSession -Body $payloadJson -ContentType "application/json" -Credential $Credential -Verbose:$false | Out-Null
                        }
                        else
                        {
                            Invoke-WebRequest -Uri $uri -Method Put -WebSession $WebSession -Body $payloadJson -ContentType "application/json" -UseDefaultCredentials -Verbose:$false | Out-Null
                        }
                        Write-Verbose "$EntirePath was uploaded to $RsFolder successfully!"
                    }
                    catch
                    {
                        throw (New-Object System.Exception("Failed to create catalog item: $($_.Exception.Message)", $_.Exception))
                    }
                    return
                }

                throw (New-Object System.Exception("Failed to create catalog item: $($_.Exception.Message)", $_.Exception))
            }
        } 

Additionally, can you describe the overall purpose of Write-RsRestCatalogItem?  Is the intention of the function to upload one item at a time, many items at a time, or to provide flexibility for both scenarios?  

The reason that I ask (in addition to the exception handling only handling one existing report in the Path Parameter array) is that the Path parameter is a string array, but the Folder and Description are not arrays.  What if we want different Folder or Description values for each item in the Path parameter?  If the function is to be truly flexible, shouldn’t we have the ability to set these parameters for each item?  Moreover, why not add a Hidden parameter so that we can hide items when we upload them.  How about a Timeout Parameter?

function Write-RsRestCatalogItem
{
    <#
        .SYNOPSIS
            This command uploads an item from disk to a report server (using the REST Endpoint).

        .DESCRIPTION
            This command uploads an item from disk to a report server (using the REST Endpoint).

        .PARAMETER Path
            Path to item to upload on disk.

        .PARAMETER RsFolder
            Folder on reportserver to upload the item to.

        .PARAMETER Description
            Specify the description to be added to the report.

        .PARAMETER Overwrite
            Overwrite the old entry, if an existing catalog item with same name exists at the specified destination.

        .PARAMETER ReportPortalUri
            Specify the Report Portal URL to your SQL Server Reporting Services Instance.

        .PARAMETER RestApiVersion
           Specify the version of REST Endpoint to use. Valid values are: "v1.0", "v2.0".
            NOTE:
                - v1.0 of REST Endpoint is not supported by Microsoft and is for SSRS 2016.
                - v2.0 of REST Endpoint is supported by Microsoft and is for SSRS 2017, PBIRS October 2017 and newer releases.

        .PARAMETER Credential
            Specify the credentials to use when connecting to the Report Server.

        .PARAMETER WebSession
            Specify the session to be used when making calls to REST Endpoint.

       …
    #>

**Comment by ClaudioESSilva** [comment]
It seems the problem in on line 294 -> https://github.com/Microsoft/ReportingServicesTools/blob/master/ReportingServicesTools/Functions/CatalogItems/Rest/Write-RsRestCatalogItem.ps1#L294 

Is a return which will end the execution.
I will submit a fix by removing the return. This way it can iterate for next $item on $path
