### ISSUE TITLE
Power BI Report Server

### ISSUE THREAD

**Issue by SMSSWS** [Microsoft/ReportingServicesTools#200]
**Do you want to request a *feature* or report a *bug*?**
Question
**What is the current behavior?**
Using 0.0.4.4    ReportingServicesTools currently on 2016 Report Server. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
No Bug to report, my usage of manipulating Folders, Users and Roles has worked extremely well.
 **What is the expected behavior?**
Is the scope of this project planned to incorporate management of Power BI Reporting Services (not the Cloud version) or is there another similar project to this one? I may just not understand the Power BI usage here, but I'm just starting with Power BI Reporting Services we've configured locally.
**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
N/A

**Comment by jtarquino** [comment]
It does already support PowerBI Report Server

**Comment by SMSSWS** [comment]
Any tips on how to learn to use it there, navigating the specific usage?
