### ISSUE TITLE
Script assumes invalid (2010) url: ReportService2010.asmx

### ISSUE THREAD

**Issue by methodbox** [Microsoft/ReportingServicesTools#212]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Doesn't work in 2012 SQL Server as it expects 2010 to be installed

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
As executed on Win Server 2012:

PS C:\Windows\system32> $proxy = New-RsWebServiceProxy -ReportServerUri $sourceURI

The output of this command is the following:

Failed to establish proxy connection to http://sql1/Reports/Pages/**ReportService2010.asmx** : There was an error
downloading 'http://sql1/Reports/Pages/ReportService2010.asmx'.
At C:\Users\*****\Documents\WindowsPowerShell\Modules\ReportingServicesTools\ReportingServicesTools\Functions\U
tilities\New-RsWebServiceProxy.ps1:114 char:9
+         throw (New-Object System.Exception("Failed to establish proxy connection ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Failed to establish proxy connection to http://sql1/Reports/Pages/ReportService2010.
   asmx : There was an error downloading 'http://sql1/Reports/Pages/ReportService2010.asmx'.

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

PS 4
Win 2012

No idea if it ever worked.

I am, unfortunately, tasked with exporting all the RDL files from this reporting server.

If you could kindly assist in how I might do that (reporting services and SQL server are on the same server) I just need to batch-export all reports in .rdl format, I would greatly appreciate it.

From what I see, your tool makes assumptions about the version of reporting services which don't match with 2012/2016, etc.

**Comment by jtarquino** [comment]
It does support 2012, seems to be you are providing a incorrect ReportServerUri , based on your post, it should be  $proxy = New-RsWebServiceProxy -ReportServerUri "http://sql1/ReportServer"

**Comment by nenea-nelu** [comment]
I'm having the same issue on Win 2012R2 Running SSRS  Reporting Services Version 12.0.6433.1, PSVersion 5.1 and thanks to [methodbox] comment above I managed to get a bit further but now I'm getting the error below:

Failed to retrieve items in '/': Exception calling "ListChildren" with "2" argument(s): "System.Web.Services.Protocols.SoapException: The operation you are attempting 
requires a secure connection (HTTPS). ---> Microsoft.ReportingServices.Diagnostics.Utilities.SecureConnectionRequiredException: The operation you are attempting 
requires a secure connection (HTTPS).
   at Microsoft.ReportingServices.WebServer.RsSoapExtension.EnsureHttpsLevel(SoapMessage message)
   at Microsoft.ReportingServices.WebServer.RsSoapExtension.ProcessMessage(SoapMessage message)
   at System.Web.Services.Protocols.SoapMessage.RunExtensions(SoapExtension[] extensions, Boolean throwOnException)
   at System.Web.Services.Protocols.SoapServerProtocol.ReadParameters()
   at System.Web.Services.Protocols.WebServiceHandler.CoreProcessRequest()"
At C:\Program Files\WindowsPowerShell\Modules\ReportingServicesTools\0.0.7.5\Functions\CatalogItems\Out-RsFolderContent.ps1:84 char:9

Does anyone have any idea how to overcome this error?
