### ISSUE TITLE
Get-RsSubscription -ReportServerUri $rsuri -path '/' - Returns Unable to find type [Microsoft.ReportingServicesTools.ConnectionHost] - Server 2016/SQL 2017

### ISSUE THREAD

**Issue by methodbox** [Microsoft/ReportingServicesTools#213]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Works on Windows 2012/SQL Server 2012, doesn't work on Windows 2016/SQL Server 2017:

Get-RsSubscription -ReportServerUri 'http://sql-server1/ReportServer' -path '/'

On 2012, I get a full output of the subscriptions,  which I intended to use to import them to the 2016/2017 server. I assume this is incompatibility with 2017, but not sure.

The only difference on the 2016 server is the url, so we can say sql-server2 vs. sql-server1

On 2016 (SQL Server 2017) I instead get this error:
```powershell
Unable to find type [Microsoft.ReportingServicesTools.ConnectionHost].
+ ... edential = ([Microsoft.ReportingServicesTools.ConnectionHost]::Creden ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Repor....ConnectionHost:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Exception while retrieving subscription(s)! You cannot call a method on a null-valued expression.
At C:\Users\*****\Documents\WindowsPowerShell\Modules\ReportingServicesTools\ReportingServicesTools\Functions\CatalogItems\Get-RsSubscription.ps1:184 char:17
+ ...             throw (New-Object System.Exception("Exception while retri ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Exception while retrieving subscription(s)! You cannot call a method on a null-valued expression.
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Same results as 2012 server.

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
2012:
```powershell
\Desktop> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1
```

Win 2016/SQL Server 2017:

```powershell
\Desktop> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  134
```

**Comment by methodbox** [comment]
It also appears the ```set-rssubscription -path``` flag ```-path``` doesn't exist (this happens on 2012, too):

```powershell
> Set-RsSubscription -ReportServerUri 'http://wci-rpt2/Reports' -Path "/"
Set-RsSubscription : A parameter cannot be found that matches parameter name 'Path'.
At line:1 char:63
+ Set-RsSubscription -ReportServerUri 'http://wci-rpt2/Reports' -Path "/"
+                                                               ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-RsSubscription], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-RsSubscription

> Get-RsSubscription -ReportServerUri 'http://wci-sql1/ReportServer' -Path "/" | Set-RsSubscription -ReportServerUri 'http://wci-rpt2/ReportServer'
 -Path "/"
Set-RsSubscription : A parameter cannot be found that matches parameter name 'Path'.
At line:1 char:147
+ ... /ReportServer' -Path "/"
+                    ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-RsSubscription], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Set-RsSubscription
```

**Comment by methodbox** [comment]
I found this version of the script, which does have $path defined, but while it throws no errors, it doesn't actually import any subscriptions under Server 2016/SQL 2017:

https://www.powershellgallery.com/packages/ReportingServicesTools/0.0.2.1/Content/Functions%5CCatalogItems%5CSet-RsSubscription.ps1

**Comment by jtarquino** [comment]
I would recommend to use the Get-Help Get-RsSubscription command to see the different set of parameters and examples of usage, probably the parameter you are looking for is RsItem

**Comment by methodbox** [comment]
Maybe you could give me a little help here?

I have given up on the previous command and exported the report subscriptions using export-rssubscriptionxml.

I'm now trying to import them on the destination server, but the get-help for this isn't helpful, as the command examples don't actually work.

This is the output for the ```import-rssubscriptionxml```:

```powershell
PS C:\>Import-RsSubscriptionXml .\MySubscriptions.xml

    Description
    -----------
    This command will import the subscriptions contained in .\MySubscriptions.xml, recreate any SRSS specific properties
    and output a PowerShell object with the result.




    -------------------------- EXAMPLE 2 --------------------------

    PS C:\>Import-RsSubscriptionXml .\MySubscriptions.xml | Set-RsSubscription -Path /Example/Report

    Description
    -----------
    This command will import the subscriptions contained in .\MySubscriptions.xml, recreate any SRSS specific properties
    and pipe the results to Set-RsSubscription which will add them to the /Example/Report report.




REMARKS
    To see the examples, type: "get-help Import-RsSubscriptionXml -examples".
    For more information, type: "get-help Import-RsSubscriptionXml -detailed".
    For technical information, type: "get-help Import-RsSubscriptionXml -full".
```

As you can see, Example 2 indicates to pass ```-path``` to the ```Set-RsSubscription``` command, which, as I've pointed out already DOES NOT EXIST in your script.

I would really appreciate some help with this rather than blowing me off, please.

**Comment by jt000** [comment]
Hey @methodbox, 

It sounds like you're mentioning a couple of issues:

1. **Missing "-Path"**: It looks like the -Path argument was replaced with the RsItem parameter in #125. I don't have context why this was this breaking change was done, but try replacing "-Path" with "-RSItem" and see if that resolves your issue.
2. **"You cannot call a method on a null-valued expression." in Get-RsSubscription**: This looks like it's coming from either the WMI host or the ReportingServiceService.exe. Which I would've thought if it was related to the Path->RsItem change it would've caught it prior to calling via the proxy. Could you check your [logs](https://docs.microsoft.com/en-us/sql/reporting-services/report-server/report-server-service-trace-log?view=sql-server-2017) and see if there's more information? It could be related to this breaking change & the script might not be doing enough to check inputs before making the call.

**Comment by jtarquino** [comment]
I would check the blogspot from the contributor to those functions @ClaudioESSilva  , for your reference is here http://redglue.eu/does-that-copy-subscriptions-too-now-it-does-new-powershell-ssrs-commands/

**Comment by methodbox** [comment]
@jt000 

I will check the logs and report back, but **as I've said, while linking to your current code**, even trying this w/the old version of the function which does accept ```-path``` still doesn't work as the help suggests it's intended.

**Comment by methodbox** [comment]
I found a work-around, even though I still feel strongly this script is broken in it's current state.

I exported an XML file of the current server using ```Export-RsSubscription -ReportServerUri http://sql1/ReportServer > exportedsubs.xml```.

I shoehorned an import of this using this on the destination server. This requires you manually start SQL Server Agent if it's not running and configure email settings in Report Server Configuration Manager under Email Settings. It doesn't appear they even need to be valid settings.

First I exported the paths using ```(Import-RsSubscriptionXml -Path .\exportedsubs.xml).path```. Because running a for loop resulted in errors when the path didn't match a given report as it seems to compare against all reports, I used Sublime multiline find/select to cut/paste those paths at the end of this command 569 times, then ran that command repeatedly until they were all imported.

```Import-RsSubscriptionXml -Path .\exportedsubs.xml | Copy-RsSubscription -RsItem '/extracted/path'```

There's probably a more efficient way of doing this, but it worked.

**Comment by jtarquino** [comment]
@methodbox  , there is tests that runs for each one of those functions, you could use them as reference in the usage if the other resources are not helpful
https://github.com/Microsoft/ReportingServicesTools/blob/master/Tests/CatalogItems/Set-RsSubscription.Tests.ps1

https://github.com/Microsoft/ReportingServicesTools/blob/master/Tests/CatalogItems/Get-RsSubscription.Tests.ps1
