### ISSUE TITLE
Bug with Set-RsRestItemDataSource - ConnectionString

### ISSUE THREAD

**Issue by Matusa69** [Microsoft/ReportingServicesTools#216]
Unable to modify ConnectionString using Set-RsRestItemDataSource, it return:
m\sql171;AdventureWorksDW2012
Failed to update data sources for '/PBIRS_Folder/01SkyPBIRSv2': The remote server returned an error: (400) Bad Request.
At C:\Program Files\WindowsPowerShell\Modules\ReportingServicesTools\0.0.4.8\Functions\CatalogItems\Rest\Set-RsRestItemDataSource.ps1:250 char:13
            throw (New-Object System.Exception("Failed to update data ...
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Failed to update data sources for '/PBIRS_Folder/01SkyPBIRSv2': The remote server returned an error: (400) Bad Request.


Changing the UserName, Password works fine.
Here is a sample code (you have to change the ReportServerURI and MyReport)

$ReportServerURI = "http://mat69vm1/PBIRSReports"
$MyReport = "/PBIRS_Folder/01SkyPBIRSv2"
$session = New-RsRestSession -ReportPortalUri $ReportServerURI

 
#recupero info su datasource
$datasources = Get-RsRestItemDataSource -WebSession $session -RsItem $MyReport
$datasources[0].ConnectionString = 'm\sql171;AdventureWorksDW2012'
write-host $datasources.ConnectionString
 
 
Set-RsRestItemDataSource -WebSession $session -RsItem $MyReport -RsItemType PowerBIReport  -DataSources $datasources 


It is normal, or not?

**Comment by jtarquino** [comment]
Modifying the connection string of Power BI Reports is not supported

**Comment by jdebarochez** [comment]
Hello, 
Is there a work around available for updating the connection string?
This [page](https://docs.microsoft.com/en-us/power-bi/report-server/connect-data-source-apis) of documentation does not mention anything regarding this lack of support. Where can we find any resource on it? Would it be supported eventually?
Thanks

**Comment by gboreki** [comment]
This was enabled in the latest release of PBIRS, you need to have September release installed. The page you referenced (published last month) is the official documentation and explains how to use it with powershell - this was not enabled in the UI.

**Comment by maurice-schleussinger** [comment]
(I know this issue is long closed, I just want to provide some additional information)

As of today, Microsoft's [documentation](https://learn.microsoft.com/en-us/power-bi/report-server/connect-data-source-apis#update-parameters-using-the-powershell-tools) explicitly mentions that the connection string can be updated with the `Set-RsRestItemDataModelParameters` function of the PowerShell tools.

However, this can only be done by setting the parameters:
<img width="882" alt="image" src="https://github.com/user-attachments/assets/eb564b5c-09df-42b5-af66-386183fff704">
