### ISSUE TITLE
Get-RsSubscription "-Path" (get-help ... -full, -showwindow, -detailed, -parameter path)

### ISSUE THREAD

**Issue by sherlockspreadsheets** [Microsoft/ReportingServicesTools#222]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I am using the cmdlet 'Get-RsSubscription' with parameter '-Path'.  The command works perfectly fine:  `Get-RsSubscription -ReportServerUri $reportServerUri -Path "/myTestFolder`". 

However, the parameter is not documented in the get-help.  These are the only documented parameters are these 5 plus the "common".  I found the syntax used online here: http://redglue.eu/does-that-copy-subscriptions-too-now-it-does-new-powershell-ssrs-commands/

>     -RsItem <String[]>
>     -ReportServerUri <String>
>     -ApiVersion <String>
>     -Credential <PSCredential>
>     -Proxy <Object>
>     <CommonParameters>
>         This cmdlet supports the common parameters: Verbose, Debug,
>         ErrorAction, ErrorVariable, WarningAction, WarningVariable,
>         OutBuffer, PipelineVariable, and OutVariable. For more information, see
>         about_CommonParameters (http://go.microsoft.com/fwlink/?LinkID=113216).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Run any of these commands below, and I don't see anything about the parameter named "-Path".  But I can use the parameter when executing the cmdlet "Get-RsSubscription".

`get-help get-rssubscription -full`
`get-help get-rssubscription -showwindow`
`help get-rssubscription -detailed`
`help get-rssubscription -parameter path`

**What is the expected behavior?**

I want to be sure that I am writing code as the cmdlet is supposed to be used.  Why is the parameter "-Path" not documented?  

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

CMD: `$PSVersionTable`

> Name                           Value
> ----                           -----
> PSVersion                      4.0
> WSManStackVersion              3.0
> SerializationVersion           1.1.0.1
> CLRVersion                     4.0.30319.42000
> BuildVersion                   6.3.9600.19170
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
> PSRemotingProtocolVersion      2.2

CMD: `Get-WmiObject -Class Win32_OperatingSystem | Format-Table Caption, ServicePackMajorVersion -AutoSize`

> Caption                           ServicePackMajorVersion
> -------                           -----------------------
> Microsoft Windows 7 Professional                        1

**Comment by jtarquino** [comment]
Path is an alias for RsItem https://github.com/Microsoft/ReportingServicesTools/blob/e5948d5c8a66eaaf86d96ffff0ebe4c2ed0367e6/ReportingServicesTools/Functions/CatalogItems/Get-RsSubscription.ps1#L57 

The common parameter across all the functions is RsItem

**Comment by sherlockspreadsheets** [comment]
Okay.  In the future, how can I find the alias?

**Comment by jtarquino** [comment]
The alias is meant for backward compatibility, for the future you should use RsItem

**Comment by sherlockspreadsheets** [comment]
Thanks for letting me know!!  I changed out my parameter name `Path` with `RsItem` and it worked exactly the same.  Thanks!
