### ISSUE TITLE
CopyRsSubscription - script with error messages

### ISSUE THREAD

**Issue by sherlockspreadsheets** [microsoft/ReportingServicesTools#226]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Cannot copy subscriptions from one server to another server

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I tried two different methods.  Both provided error messages.  

>**Method 1:**  `Get-RsSubscription` piped to `export-rssubscriptionxml`, then `import-rssubscriptionxml` piped to `Copy-RsSubscription`
>
> **Method 2:** `Get-RsSubscription` piped to `Copy-RsSubscription`

**What is the expected behavior?**

Copy subscriptions from one server to another server

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

I do not know if this has worked in other versions; I have only tried the version I am currently using.  

$psversiontable

```
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.19170
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

[Environment]::OSVersion | ft -autosize

```
Platform ServicePack    Version        VersionString
-------- -----------    -------        -------------
 Win32NT Service Pack 1 6.1.7601.65536 Microsoft Windows NT 6.1.7601 Service Pack 1
```
[CopyRsSubscription_script with error messages.txt](https://github.com/Microsoft/ReportingServicesTools/files/3098293/CopyRsSubscription_script.with.error.messages.txt)

**Comment by sherlockspreadsheets** [comment]
Any updates on how I can use copy-subscription to move a subscription from ServerA to ServerB?

**Comment by jtarquino** [comment]
Have you checked the article of the contributor of those functions http://linkredglue.com/does-that-copy-subscriptions-too-now-it-does-new-powershell-ssrs-commands/
