### ISSUE TITLE
Out-RsRestCatalogItem - pbix not refreshed

### ISSUE THREAD

**Issue by PowerDAX** [microsoft/ReportingServicesTools#230]
bug

running powershell script to connect and download latest pbix file using Out-RsRestCatalogItem

the report(s) in question are updated daily

export works fine - however, the data in the pbix file seem to be only updated as of the last upload

the data in the pbix file is expected to be refreshed as of the last successful refresh on the Power BI Report Server

not sure what previous behavior was

am hoping that the pbix file is updated along w/ the backend ssas that is running.  the intent is to download the latest pbix file, export to csv.

**Comment by jtarquino** [comment]
It is the behavior of the server, the pbix file (same than rdl) reflects the initial upload state
