### ISSUE TITLE
Set-RsSharedDataSource  -ErrorAction:SilentlyContinue

### ISSUE THREAD

**Issue by Carsten3000** [microsoft/ReportingServicesTools#231]
I deployed a lot of reports and now i am trying update all their data sources  at once:

```
Get-RsFolderContent	-ReportServerUri $SSRS_WebServiceURL -RsFolder /00Standardberichte -Recurse | Where-Object {$_.TypeName -eq 'Report'} | ForEach-Object {
    Set-RsSharedDataSource -ReportServerUri $SSRS_WebServiceURL -Path $_.Path -DataSourceName DataSource_DW  -DataSourcePath '/00Standardberichte/Data Sources/DataSource_DW' -ErrorAction:SilentlyContinue
    Set-RsSharedDataSource -ReportServerUri $SSRS_WebServiceURL -Path $_.Path -DataSourceName DW_Windows_Authentication -DataSourcePath '/00Standardberichte/Data Sources/DW_Windows_Authentication' -ErrorAction:SilentlyContinue
}

```
I get this error: 

> /00Standardberichte/Produktion/01 Lagerumschlag pro Tag does not contain a dataSource reference with name DW_Windows_Authentication
> In C:\Program Files\WindowsPowerShell\Modules\ReportingServicesTools\0.0.4.9\Functions\CatalogItems\Set-RsDataSourceReference.ps1:93 Zeichen:17
> + ...             throw "$item does not contain a dataSource reference with ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (/00Standardberi..._Authentication:String) [], RuntimeException
>     + FullyQualifiedErrorId : /00Standardberichte/Produktion/01 Lagerumschlag pro Tag does not contain a dataSource reference with name DW_Windows_Authentication

Some of the reports don't have a data source DW_Windows_Authentication, i tried to bypass this with the parameter -ErrorAction:SilentlyContinue (as stated in the documentation).

Any idea how i can achieve this?

Thanks a a lot!

**Comment by jtarquino** [comment]
you probably can use a try catch block in the set-rsshareddataousrce
