### ISSUE TITLE
New-RsWebServiceProxy throws error when trying to access a remote server

### ISSUE THREAD

**Issue by rusticMire** [microsoft/ReportingServicesTools#235]
**Do you want to request a *feature* or report a *bug*?**
bug 

**What is the current behavior?**

When I invoke the below command 

`New-RsWebServiceProxy -ReportServerUri New-RsWebServiceProxy -ReportServerUri http://<ServerName>/<ReportServer> -verbose`

I get the following error 

> VERBOSE: Establishing proxy connection to http://\<ServerName\>/\<ReportServer\> /ReportService2010.asmx/ReportService2010.asmx...
Failed to establish proxy connection to http://\<ServerName\>/\<ReportServer\> /ReportService2010.asmx/ReportService2010.asmx : The HTML document does not contain Web service discovery
information.
At C:\Program Files\WindowsPowerShell\Modules\ReportingServicesTools\0.0.5.0\Functions\Utilities\New-RsWebServiceProxy.ps1:114 char:9
\+         throw (New-Object System.Exception("Failed to establish proxy ...
\+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Failed to establish proxy connection to http://\<ServerName\>/\<ReportServer\> /ReportService2010.asmx/ReportService2010.asmx : The HTML document does not contain
    Web service discovery information.

When I hit the **ReportServerURI** in the browser, I get asked for credentials and upon entering them, I am able to see the report server details. The  Server is a remote server and not localhost and the credentials are same as the ones that I have logged in with from which I am invoking the script. I have passed the `-credential` parameter to enter credentials but I get the same error. 

Also, the script works fine for a **localhost**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Try to retrieve a proxy for the reporting server using the below command given the reporting server is a remote server and not the localhost 
`New-RsWebServiceProxy -ReportServerUri New-RsWebServiceProxy -ReportServerUri http://<ServerName>/<ReportServer> -verbose`

**What is the expected behavior?**

This command should create and return a web service proxy  

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

The version I am using is 5.1.14393.2969. I am not sure if this is a version related issue but mostly a design issue.

**Comment by jtarquino** [comment]
from your logs you seem to have duplicated endpoint
http://<ServerName>/<ReportServer> /ReportService2010.asmx/ReportService2010.asmx

What exactly are you passing as Uri, you should just pass the server name and the reportserver endpoint without the asmx

**Comment by rusticMire** [comment]
That's a formatting error which I edited out now. It most likely looks like some problem with the configuration as I am able to run the command without errors from a particular domain joined server

**Comment by Hemanthreddy69** [comment]
command output: 
VERBOSE: Performing the operation "Upload all contents in folder to /CustomReports" on target ".".
VERBOSE: Establishing proxy connection to 
https://reports.dvlp.careadvance.bcbst.com/ReportServer/ReportService2010.asmx...
Failed to establish proxy connection to https://reports.dvlp.careadvance.bcbst.com/ReportServer/ReportService2010.asmx 
: There was an error downloading 'https://reports.dvlp.careadvance.bcbst.com/ReportServer/ReportService2010.asmx'.
At C:\Program Files\WindowsPowerShell\Modules\WindowsPowerShell\Modules\ReportingServicesTools\ReportingServicesTools\F
unctions\Utilities\New-RsWebServiceProxy.ps1:114 char:9
+         throw (New-Object System.Exception("Failed to establish proxy ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Failed to establish proxy connection to https://reports.dvlp.careadvance.bcbst.com/Repor 
   tServer/ReportService2010.asmx : There was an error downloading 'https://reports.dvlp.careadvance.bcbst.com/Report  
  Server/ReportService2010.asmx'.

**Comment by Hemanthreddy69** [comment]
Any help, I have tried many options and nothing worked for the above issue

**Comment by thaismuller** [comment]
i am with the same problems in my script

**Comment by MasTristan** [comment]
> i am with the same problems in my script

Did you find a solution ? I have the same issue
