### ISSUE TITLE
Write-RsCatalogItem & Write-RsFolderContent don't support uploading a Shared DataSource file (.rds)

### ISSUE THREAD

**Issue by SQLvariant** [Microsoft/ReportingServicesTools#24]
Write-RsCatalogItem & Write-RsFolderContent don't support uploading a Shared DataSource file (.rds)

When you try to run a command like the following, your receive an error message:
`Write-RsCatalogItem -ReportServerUri http://localhost/ReportServer_SQL2016 -Path 'C:\SSIS Reporting Pack\Reports\SSISCatalog.rds' -Destination /SSISReportingPack -Verbose`

> Currently only .rdl, .rsds and .rsd files are supported
> At C:\Users\sql2k\Documents\WindowsPowerShell\Modules\ReportingServicesTools\Functi
> ons\Common\Get-ItemType.ps1:12 char:18

When will Write-RsCatalogItem & Write-RsFolderContent support extremely common scenarios like uploading a Shared DataSource file (.rds)?

**Comment by jbrant** [comment]
Wholeheartedly agree - this package and all of the amazing utility it provides is largely a waste until this issue is addressed.

**Comment by parthsha** [comment]
I will look into this and get back to you as soon as possible.

**Comment by parthsha** [comment]
I am going to close this ticket since I have added support for it. Please create a new one if you experience any issues while uploading .rsds files.
