### ISSUE TITLE
Remove-RsRestCatalogItem Fails when using RestApiVersion "v1.0"

### ISSUE THREAD

**Issue by dpo007** [microsoft/ReportingServicesTools#245]
If I try to specify v1.0 as the RestApiVersion option for Remove-RsRestCatalogItem I receive the following error:

`Remove-RsRestCatalogItem : Cannot validate argument on parameter 'RestApiVersion'. The argument "v1.0" does not belong to the set "v2.0" specified by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.`

Command run: 

`Remove-RsRestCatalogItem -RsItem $remoteReportPath -ReportPortalUri $ssrsServer -RestApiVersion 'v1.0'`

Using -RestApiVersion 'v1.0' with Write-RsRestCatalogItem works as expected.

I'm currently using v0.0.5.0 (latest found via Install-Module), with PowerShell 5.1 (Windows 10).

**Comment by jtarquino** [comment]
Some of the commands like this [one](https://github.com/microsoft/ReportingServicesTools/blob/e5948d5c8a66eaaf86d96ffff0ebe4c2ed0367e6/ReportingServicesTools/Functions/CatalogItems/Rest/Remove-RsRestCatalogItem.ps1#L20) only supports v2.0 which is the public API

What is the scenario you are trying to solve with the v1.0?

**Comment by dpo007** [comment]
I'm trying to delete plain-text resource file(s) that I've added with Write-RsRestCatalogItem (as it seems write-RSCatalogItem won't allow uploading anything but RDS, data objects, and png/jpgs).

**Comment by dpo007** [comment]
Good news!  While Write-RSCatalogItem won't let me add Text files (only reports, data objects adn png/jpg files), Remove-RSCatalogItem DOES remove them, so I'm good. ;)
