### ISSUE TITLE
Module Import Issues, No Digital Signature

### ISSUE THREAD

**Issue by hud87** [microsoft/ReportingServicesTools#246]
Below is the error I'm getting, I cannot import due to the module not having a digital signature. I can't change my execution policy due to Company policy... Please advise....Appreciate your help.

PS C:\windows\system32> Import-Module -Name ReportingServicesTools
Import-Module : File C:\Program Files\WindowsPowerShell\Modules\ReportingServicesTools\ReportingServicesTools.psm1 cannot be loaded. The file C:\Program 
Files\WindowsPowerShell\Modules\ReportingServicesTools\ReportingServicesTools.psm1 is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, 
see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ Import-Module -Name ReportingServicesTools
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [Import-Module], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by jtarquino** [comment]
unfortunately we don't have plans to sign it in the short term.
If we choose to sign it it will be in the powershell gallery https://www.powershellgallery.com/packages/ReportingServicesTools

I don't think that it will work, but have you tried to install it from the fallery instead?

**Comment by hud87** [comment]
Thanks for the quick reply. I’m fairly new to PowerShell so please forgive me, what is the fallery? Did you mean gallery?

I’m working on a server with no ability to reach the internet too. I’m having to manually download the files and dump them into my folder with other modules already in use.

Thanks again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jtarquino** [comment]
Yes I meant the gallery
