### ISSUE TITLE
Out-RsFolderContent: sub folder issues 

### ISSUE THREAD

**Issue by hud87** [microsoft/ReportingServicesTools#247]
I have a report folder that contains sub folders. When running this script:

Out-RsFolderContent -ReportServerUri 'http://ServerName/reports' -Path '/MainFolder'  -Destination 'C:\tempSSRS_Reports' -Proxy 'proxy.location.com'

I get the following errors related to 'ListChildren'. Is this a bug or is there more code needed?
I try and add the -Recurse option but I get the same error.

Failed to retrieve items in '/MainFolder': Method invocation failed because [System.String] does not contain a method named 'ListChildren'.
At C:\Program Files\WindowsPowerShell\Modules\ReportingServicesTools\Functions\CatalogItems\Out-RsFolderContent.ps1:84 char:9
+         throw (New-Object System.Exception("Failed to retrieve items  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Failed to retrieve items in '/MainFolder': Method invocation failed because [System.String] does not contain a method named 'ListChildren'.

Appreciate your help.

**Comment by jtarquino** [comment]
I haven't seen that issue and there is test coverage for Out-RsFolderContent , I suspect its related to the proxy parameter you are using, what you need to pass as a parameters in the proxy is an object that you get calling New-RsWebServiceProxy
Usually you don't need to pass a proxy its only for advanced scenarios
