### ISSUE TITLE
Out-RsFolderContent needs additional feature(s)

### ISSUE THREAD

**Issue by gorkam23** [microsoft/ReportingServicesTools#249]
I am working with Server 2016/PowerShell 5.1

I am trying to write a unified script to migrate a whole environment using the ReportingServicesTools.

One of the first problems I see is the fact that the existing credentials for the data sources are not being exported.  Due to this, even though I can re-import the data sources, I still have to go into the GUI to reattach them.  I would like the ability to export the security and then reimport it so the datasources would be live assuming the same connecting database was in place on the new server.  

I looked at the .XML and I don't see a field that would export that security.  

<DataSourceDefinition>
<Extension>SQL</Extension>
<ConnectString>Data Source=LocalHost; Initial Catalog=WideWorldImporters;
</ConnectString><UseOriginalConnectString>False</UseOriginalConnectString>
<OriginalConnectStringExpressionBased>False</OriginalConnectStringExpressionBased>
<CredentialRetrieval>Store</CredentialRetrieval>
<WindowsCredentials>False</WindowsCredentials>
<ImpersonateUser>False</ImpersonateUser>
<UserName>reportadmin</UserName>
<Enabled>True</Enabled></DataSourceDefinition>

I looked at the raw code for both Out-RsFolderContent and Out-RsCatalogItem and did not see a part that would allow this.  

Thank you.  I'm happy to look further, but I need to know where to go...

**Comment by jtarquino** [comment]
Our APIs don't expose the credentials in any way, for the scenario of migrating a entire environment the best approach will be restoring the catalog database in the new environment
