### ISSUE TITLE
Out-RsCatalogItem Does Not Support TypeName of PowerBIReport

### ISSUE THREAD

**Issue by SQLvariant** [Microsoft/ReportingServicesTools#25]
I am trying to automate deployment & testing of my Power BI reports in the RS Stand Alone Preview however `Out-RsCatalogItem` does not support `TypeName `of `PowerBIReport`.

```
PS C:\temp> 
Out-RsFolderContent -ReportServerUri http://localhost/RSSA -RsFolder /BasicSalesReport -Destination c:\temp\
Exception calling "ListChildren" with "2" argument(s): "System.Web.Services.Protocols.SoapException: The operation you are attempting on item 
'/BasicSalesReport' is not allowed for this item type. ---> Microsoft.ReportingServices.Diagnostics.Utilities.WrongItemTypeException: The operation 
you are attempting on item '/BasicSalesReport' is not allowed for this item type.
   at Microsoft.ReportingServices.Library.ReportingService2005Impl.ListChildren(String Item, Boolean Recursive, CatalogItemList& CatalogItems)
   at Microsoft.ReportingServices.WebServer.ReportingService2010.ListChildren(String ItemPath, Boolean Recursive, CatalogItem[]& CatalogItems)"
At C:\Users\sql2k\Documents\WindowsPowerShell\Modules\ReportingServicesTools\Functions\CatalogItems\Get-RsFolderContent.ps1:82 char:9
+         $Proxy.ListChildren($RsFolder, $Recurse)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SoapException
 

PS C:\temp> 
```

I would like to be able to export this report before overwriting it with a new version.

PowerShell 5.1 using SSRS Stand Alone Preview & Power BI Desktop (SQL Server Reporting Services)

**Comment by jtarquino** [comment]
The PBI reports use a different API which is not supported yet by the PowerShell modules

**Comment by SQLvariant** [comment]
Any update on this one?

**Comment by jtarquino** [comment]
GA as kept as pretty busy, however contributions to support the scenario are more than welcome

**Comment by parthsha** [comment]
You can now use Out-RsRestCatalogItem to download Power BI Reports, Mobile Reports, Excel Workbooks and KPIs. Unfortunately, this functionality cannot be added to Out-RsCatalogItem because of API limitations. I will close this issue for now, however feel free to open it if you have any additional comments.
