### ISSUE TITLE
Set-RsSubscription - -Path parameter referenced in Import-RsSubscriptionXML examples

### ISSUE THREAD

**Issue by gorkam23** [microsoft/ReportingServicesTools#250]
Working with the Import-RsSubscriptionXML cmdlet, and one of its two examples references this sample:

-------------------------- EXAMPLE 2 --------------------------

PS C:\>Import-RsSubscriptionXml .\MySubscriptions.xml | Set-RsSubscription -Path /Example/Report

Description
-----------
This command will import the subscriptions contained in .\MySubscriptions.xml, recreate any SRSS specific
properties
and pipe the results to Set-RsSubscription which will add them to the /Example/Report report.

Yet, -path is not a valid parameter for Set-RsSubscription.

Any ideas on how to use Import-RsSubscriptionXML?

Thank you!

**Comment by jtarquino** [comment]
The sample seems to be incorrect, check the parameters for Set-RsSubscription , I think your need to call before Get-RsSubscription which has the Path

**Comment by gorkam23** [comment]
Do you mean example in the Import-RsSubscriptionXML cmdlet?
