### ISSUE TITLE
Example for New-RsRestFolder uses -RsFolder twice

### ISSUE THREAD

**Issue by marclancy** [microsoft/ReportingServicesTools#259]
bug

The example given is: `New-RsRestFolder -RsFolder MyNewFolder -RsFolder /`
Creates a new folder called "MyNewFolder" under "/" parent folder.

Which gives the error: Cannot bind parameter because parameter 'RsFolder' is specified more than once.

I believe the correct syntax should be: `New-RsRestFolder -FolderName MyNewFolder -RsFolder /`

**Comment by jtarquino** [comment]
Thank you, would you mind to send a Pull Request with the documentation update
