### ISSUE TITLE
Configure the newly installed but not configured SSRS

### ISSUE THREAD

**Issue by alvibol** [microsoft/ReportingServicesTools#263]
I'm new to powershell, please help me. How can I use this module to configure the newly installed but not configured SSRS. Is it possible? Any example would help me.

**Comment by alvibol** [comment]
>Set-RsUrlReservation
Get-WmiObject : Wrong namespace  "root\Microsoft\SqlServer\ReportServer\RS_MSSQLSERVER\v13\Admin"
C:\windows\system32\windowspowershell\v1.0\Modules\ReportingServicesTools\ReportingServicesTools\Functions\Utilities\Ne
w-RsConfigurationSettingObject.ps1:100 sign:19
+     $wmiObjects = Get-WmiObject @getWmiObjectParameters
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand

Microsoft server 2012 R2, Microsoft SQL Server 2012

> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

**Comment by jtarquino** [comment]
What version are you using?
depending on the version you need to specify the parameter -ReportServerVersion SQLServervNext

You can see the list of versions here https://github.com/microsoft/ReportingServicesTools/blob/e5948d5c8a66eaaf86d96ffff0ebe4c2ed0367e6/ReportingServicesTools/Libraries/library.ps1#L92
