### ISSUE TITLE
Write-Information (v5) is used but only v3 is required

### ISSUE THREAD

**Issue by ctrlbold** [Microsoft/ReportingServicesTools#27]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Write-Information is used. Write-Information was introduced by PowerShell v5 but the psd1 only requires v3.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Install Win2012, don't update WMF to 5.0, type Write-Information from the command line

**What is the expected behavior?**

Either require v5 or update the code to be v3 compatible (preferred)

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

v3 on Server 2012

**Comment by FriedrichWeinmann** [comment]
Hi Chrissy,

it's resolved in my PR. We're currently working out the last kinks, soo ... once that's done your issue here will too be gone :)

Cheers,
Fred

**Comment by ctrlbold** [comment]
😻

**Comment by ctrlbold** [comment]
Nary a Write-Information left! Closing issue 👍
