### ISSUE TITLE
Changing Connection String via API with no internet connection

### ISSUE THREAD

**Issue by BoscoMoroni** [microsoft/ReportingServicesTools#271]
BUG:
Recently installed Power BI Report Server. 3 instances installed across development, test, and production. Need a method for promoting content without having to connect to the individual environments again in the desktop application. To do this we are trying to promote the same content through each environment and then execute an API to amend the connection string.
Research suggests we need to install ReportingServicesTools in PowerShell in order to execute the change in connection string.
https://docs.microsoft.com/en-us/power-bi/report-server/connect-data-source-apis
Unfortunately our report server doesn’t have an external internet connection to call the ReportingServicesTools or even when creating the functions manually it needs a New-RsRestSession to progress. After installing this function and trying to execute we get the below error.
PS C:\Users\*****> New-RsRestSession
Unable to find type [Microsoft.ReportingServicesTools.ConnectionHost].
At line:39 char:29
+ ... ortalUri = ([Microsoft.ReportingServicesTools.ConnectionHost]::Report ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Repor....ConnectionHost:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
The question is then as all of the details of the connection strings and data sources are stored on the server, is there a way of making these changes via API without an internet connection?
Many thanks,
Luke

**Comment by jtarquino** [comment]
Seems to be you want to install it in a machine without internet access
The tools are available in the powershell gallery https://www.powershellgallery.com/packages/ReportingServicesTools 

There is some help in stackoverflow on how to install modules
https://stackoverflow.com/questions/37486587/powershell-v5-how-to-install-modules-to-a-computer-having-no-internet-connecti

Also you could do the equivalent of a local dev installation which is downloading the entire repo and then run Import-Module .\ReportingServicesTools.psd1
