### ISSUE TITLE
import subscriptions

### ISSUE THREAD

**Issue by vondravl** [microsoft/ReportingServicesTools#273]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
I'm able to export subscriptions to xml, but unable to import this xml to other report
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
```
#------------------------------------------------------
#Declare SSRS URI
$sourceRsUri = "https://rpting.domain.local/ReportServer"

#Declare Proxy so we dont need to connect with every command -Credential $cred
$proxy = New-RsWebServiceProxy -ReportServerUri $sourceRsUri

Import-RsSubscriptionXml "C:\Backups\SSRS_Subscriptions\PM_VacationOfPeopleForProjects_2020-02-03.xml" | Copy-RsSubscription -Proxy $proxy -RsItem "/Not finished/_VacationReports"

```

> Failed to establish proxy connection to http://localhost/reportserver/ : Failed to establish proxy connection to http://localhost/reportserver/ReportService2010.asmx : There was an error dow
> nloading 'http://localhost/reportserver/ReportService2010.asmx'.
> At C:\Users\vondra\Documents\WindowsPowerShell\Modules\ReportingServicesTools\ReportingServicesTools\Functions\Utilities\New-RsWebServiceProxy.ps1:89 char:17
> + ...             throw (New-Object System.Exception("Failed to establish p ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (:) [], Exception
>     + FullyQualifiedErrorId : Failed to establish proxy connection to http://localhost/reportserver/ : Failed to establish proxy connection to http://localhost/reportserver/ReportService201 
>    0.asmx : There was an error downloading 'http://localhost/reportserver/ReportService2010.asmx'.

Neither work Set-RsSubscription. 
**What is the expected behavior?**
Import subscriptions by batch
**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
Powershell
Major:5  Minor:1  Build:17763  Revision:771

ReportingServicesTools version  0.0.5.1

**Comment by jtarquino** [comment]
The error you describe shows an issue connecting to the reportserver at localhost/reportserver, so looks like there is an issue with your $proxy variable, I would try to use the -ReportServerUri parameter

**Comment by vondravl** [comment]
that gives me exactly same error, also if I export subscription I also use proxy and it works well, that means it is not working only in import and copy subscription

**Comment by jtarquino** [comment]
I would try to run it locally in the server where you want to import the subscription

**Comment by vondravl** [comment]
Yes from the server where reporting server is installed are those error logs which I pasted here. 

The puzzle is why this works:
`Get-RsSubscription -Proxy $proxy -Path '/PM/_VacationReports' | Export-RsSubscriptionXml "PM_VacationOfPeopleForProjects_.xml"`

and this one is not working
`Import-RsSubscriptionXml "C:\Backups\SSRS_Subscriptions\PM_VacationOfPeopleForProjects_2020-02-03.xml" | Copy-RsSubscription -Proxy $proxy -RsItem "/Not finished/_VacationReports"`
 and the error warning says failed to establish connection. I can change proxy for -ReportServerUri parameter and the result is same, first one works and second one not

**Comment by jtarquino** [comment]
I suggest you enable verbose logging and troubleshoot the issue, we do have coverage in the test for the scenario https://github.com/microsoft/ReportingServicesTools/blob/master/Tests/CatalogItems/Copy-RsSubscription.Tests.ps1 and is passing consistently, which made me suspect there is caused by some environmental issue
