### ISSUE TITLE
Set-RsRestItemDataSource failed with 405 Method not allowed

### ISSUE THREAD

**Issue by JSchrocke** [microsoft/ReportingServicesTools#275]
Hi,
I am trying to modify the ODATA data source for an uploaded PBIX report on PowerBI ReportServer.

$dataSources = Get-RsRestItemDataSource -ReportPortalUri https://ReportServerURL -RsItem '/PBI Report'

$dataSources.ConnectionString # Provides me the existing URL for the ODATA

$dataSources.ConnectionString = "https://URL/..."

Set-RsRestItemDataSource -RsItem '/PBI Report' -RsItemType PowerBIReport -DataSources $dataSources  # This fails 

Failed to update data sources for '/PBI Report': The remote server returned an error: (405) Method Not
Allowed.
At C:\Program
Files\WindowsPowerShell\Modules\ReportingServicesTools\Functions\CatalogItems\Rest\Set-RsRestItemDataSource.ps1:249
char:13
+             throw (New-Object System.Exception("Failed to update data ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Failed to update data sources for '/PBI Report': The remote server returned a
   n error: (405) Method Not Allowed.

Is this not allowed to change the data source for and ODATA data source or what could be wrong here?

Installed version :
Script     0.0.5.2    ReportingServicesTools

**Comment by jtarquino** [comment]
it is not supported yet to modify the connection string of a PBIX report
