### ISSUE TITLE
Error while executing through PSSession

### ISSUE THREAD

**Issue by chintansp** [microsoft/ReportingServicesTools#290]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Error while executing through PSSession

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

` $proxy = New-RsWebServiceProxy -ReportServerUri $reportServerUri

Get-RsFolderContent -Proxy $proxy -ReportServerUri $reportServerUri -RsFolder $sourceRSFolder | Where-Object TypeName -eq 'Report' |
Select-Object -ExpandProperty Path |
Out-RsCatalogItem -Proxy $proxy -ReportServerUri $reportServerUri -Destination $downloadFolder`

While executing above code from PSSession i am getting below error:

Failed to establish proxy connection to http://101.112.20.1/ReportServer/ReportService2010.asmx : There was a
downloading 'http://101.112.20.1/ReportServer/ReportService2010.asmx'.
+ CategoryInfo : OperationStopped: (:) [], Exception
+ FullyQualifiedErrorId : Failed to establish proxy connection to http://101.112.20.1/ReportServer/Report
2010.asmx : There was an error downloading 'http://101.112.20.1/ReportServer/ReportService2010.asmx'.

**What is the expected behavior?**

it should connect to report server
**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  3471
Window server 2016

**Comment by jtarquino** [comment]
From the error seems to be you don't have connectivity or don't have permissions, verify is the right URL connecting from a browser
