### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ejmendozao** [microsoft/ReportingServicesTools#293]
Is there an example of how to use these commands?

**Comment by jtarquino** [comment]
The samples are part of the commands , you can use [Get-Help](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/get-help?view=powershell-7) 
The community has written some [articles like](https://www.mssqltips.com/sqlservertip/4738/powershell-commands-for-sql-server-reporting-services/) and others that a search engine should be able to find
