### ISSUE TITLE
Please update the scripts for PBIRS

### ISSUE THREAD

**Issue by vansree** [microsoft/ReportingServicesTools#294]
Feature request: Please update the scripts for PBIRS. Scripts fail if we have PBI desktop files.

**Comment by jtarquino** [comment]
Would you mind to provide additional details about what script is failing for you?

**Comment by vansree** [comment]
Sorry for late reply

Say, if I have PBI desktop files on PBIRS (Power BI Report Server), 
   Get-RsFolderContent ... works
   Out-RsFolderContent ... sometimes gives me error, sometimes no error 
                                **but wont download PBIX files**

**Comment by jtarquino** [comment]
PowerBI reports are supported with the new rest api, there is a equivalent Out-RsRestFolderContent that you should try

**Comment by vansree** [comment]
Thanks for the reply. 

Please update the home page (documentation) to say that Power BI Report Server - Power BI reports has to be using Rest api.
