### ISSUE TITLE
Out-RsFolderContent doesn't export Power BI Reports

### ISSUE THREAD

**Issue by DAZCUK46** [microsoft/ReportingServicesTools#299]
Out-RsFolderContent doesn't export Power BI Reports (PBIX's) on the Power BI Report Server all other items are exported as expected.

**Comment by jtarquino** [comment]
PBIX is only supported in Out-RsRestFolderContent

**Comment by DAZCUK46** [comment]
Thanks for coming back so quickly and sorry my bad still getting used to using Github and should have reviewed closed issues prior as see it's been asked before.  


One thing i've found whilst eventually getting it to work is the examples may need updating?

I had to use 'http://ReportServer/Reports' not 'http://ReportServer/ReportServer' to get it to work was getting this error when using '....ReportServer' 

"Failed to create a new session to http://ReportServer/ReportServer/api/v2.0/me : Invalid Report Portal Uri specified!
Please make sure ReportPortalUri is the URL to the Report Portal!"

Example that didn't work as per the examples in the script:
Out-RsRestFolderContent -ReportPortalUri 'http://ReportServer/ReportServer' -RsFolder "/" -Destination C:\Reports\ -Recurse

Example that worked:
Out-RsRestFolderContent -ReportPortalUri 'http://ReportServer/Reports' -RsFolder "/" -Destination C:\Reports\ -Recurse
