### ISSUE TITLE
contribution

### ISSUE THREAD

**Issue by crshnbrn66** [Microsoft/ReportingServicesTools#3]
this gist has a bunch of functions I've written for SSRS and I have more updates to it that I've done. 
https://gist.github.com/crshnbrn66/b10e43ef0dadf7f4eeae620428b2cdd9
I can update and post here.... This module that I wrote I'm using it with TFS build and release in a ci scenario (tfs 2015 r3).

**Comment by jtarquino** [comment]
Hi Thom, of course we welcome any contribution, that is the main idea behind this project, feel free to fork the branch and send a pull request.

**Comment by crshnbrn66** [comment]
I have built CI around the scripting I've written for SSRS before I knew this repo was here. Is there a community SSRS that is available? That can be hooked up with VSO or something like that??

**Comment by jtarquino** [comment]
You mean a SSRS Server to run the scripts against or a free edition of SSRS (like the https://www.microsoft.com/en-us/cloud-platform/sql-server-editions-express) 

If is the server we don't have something like that, it presents a interesting of challenges about how to maintain it, other option for CI is to create mocks using pester to test the scripts as pure unit tests.
