### ISSUE TITLE
Piping between Get-RsFolderContent and Remove-RsCatalogItem doesn´t work as expected

### ISSUE THREAD

**Issue by erimaja** [Microsoft/ReportingServicesTools#30]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug

**What is the current behavior?**
An example from the documentation isn´t working

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Get-Help Remove-RsCatalogItem -example

-------------------------- EXAMPLE 2 --------------------------

    PS C:\>Get-RsCatalogItems -ReportServerUri http://localhost/ReportServer_SQL2016 -RsFolder '/SQL Server Performance Dashboard' |

    Out-GridView -PassThru |
    Remove-RsCatalogItem -ReportServerUri http://localhost/ReportServer_SQL2016

    Description
    -----------
    Gets a list of items from the SQL Server Performance Dashboard folder in a GridView from an SSRS instance names SQL2016 and allows the user to select items to be removed, after clicking "OK", only
    the items selected will be removed.

Exception occurred while deleting catalog item 'Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tserver_ReportService2010_asmx.CatalogItem'! Exception
calling "DeleteItem" with "1" argument(s): "System.Web.Services.Protocols.SoapException: The path of the item
'Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tserver_ReportService2010_asmx.CatalogItem' is not valid. The full path must be less than 260 characters
long; other restrictions apply. If the report server is in native mode, the path must start with slash. ---> Microsoft.ReportingServices.Diagnostics.Utilities.InvalidItemPathException: The
path of the item 'Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tserver_ReportService2010_asmx.CatalogItem' is not valid. The full path must be less than
260 characters long; other restrictions apply. If the report server is in native mode, the path must start with slash.
   at Microsoft.ReportingServices.Library.ReportingService2005Impl.DeleteItem(String Item, Guid batchId)
   at Microsoft.ReportingServices.Library.ReportingService2005Impl.DeleteItem(String Item)
   at Microsoft.ReportingServices.WebServer.ReportingService2010.DeleteItem(String ItemPath)"
At C:\kitsune\ReportingServicesTools\Functions\CatalogItems\Remove-RsCatalogItem.ps1:82 char:21

**What is the expected behavior?**

Delete the catalog items. For example this one works:
(Get-RsFolderContent -RsFolder / ).path |  Remove-RsCatalogItem -ReportServerUri http://localhost/reportserver

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

**Comment by dakotagurl** [comment]
I have the same error.  Using SQL 2012.
