### ISSUE TITLE
New-RsWebServiceProxy: The command 'New-RsWebServiceProxy' was found in the module 'ReportingServicesTools', but the module could not be loaded.

### ISSUE THREAD

**Issue by TobiasEl** [microsoft/ReportingServicesTools#313]
Hi, I have installed the SSRS module and I have te following error:
"New-RsWebServiceProxy: The command 'New-RsWebServiceProxy' was found in the module 'ReportingServicesTools', but the
module could not be loaded. For more information, run 'Import-Module ReportingServicesTools'."

I'm new on Power Shell, so I don't really know how to solve it. I found this module in this link: https://stackoverflow.com/questions/46783093/download-all-ssrs-reports

Since I want to download al the mobile reports (.rsmobile) from my SSRS. I'm using the following commands:
#####################################################################################
$sourceRsUri = "http://desktop-2345/Reports/ReportService2019.asmx?wsdl"

#Declare Proxy so we dont need to connect with every command
$proxy = New-RsWebServiceProxy -ReportServerUri $sourceRsUri

#Output ALL Catalog items to file system
Out-RsFolderContent -Proxy $proxy -RsFolder / -Destination 'C:\SSRS_Out' -Recurse
#####################################################################################

This is the full error:

New-RsWebServiceProxy: The command 'New-RsWebServiceProxy' was found in the module 'ReportingServicesTools', but the
module could not be loaded. For more information, run 'Import-Module ReportingServicesTools'.
Online: 4 Character: 10
+ $ proxy = New-RsWebServiceProxy -ReportServerUri $ sourceRsUri
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo: ObjectNotFound: (New-RsWebServiceProxy: String) [], CommandNotFoundException
    + FullyQualifiedErrorId: CouldNotAutoloadMatchingModule

Out-RsFolderContent: The command 'Out-RsFolderContent' was found in the module 'ReportingServicesTools', but the
module could not be loaded. For more information, run 'Import-Module ReportingServicesTools'.
Online: 7 Character: 1
+ Out-RsFolderContent -Proxy $ proxy -RsFolder / -Destination 'C: \ SSRS_O ...
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo: ObjectNotFound: (Out-RsFolderContent: String) [], CommandNotFoundException
    + FullyQualifiedErrorId: CouldNotAutoloadMatchingModule 

My PowerShell version is: 

Name                           Value
----                           -----
PSVersion                      5.1.18362.1171
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1171
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Plis I need to download all my mobile report and datasets

**Comment by jtarquino** [comment]
You don't need to declare the web proxy , you could just call the Out-RsFolderContent

**Comment by TobiasEl** [comment]
The solution was change the permissions to unrestricted
