### ISSUE TITLE
Get-RsDeploymentConfig doesn't check for NULL values

### ISSUE THREAD

**Issue by selsine** [microsoft/ReportingServicesTools#319]
I'm not that familiar with powershell but when I try to run Get-RsDeploymentConfig on my SSRS project file I'm getting the following error:

```
Get-Content : Cannot bind argument to parameter 'Path' because it is null.
At line:1 char:29
+ [XML]$rptproj = Get-Content $RsProjectFile
+                             ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-Content], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.GetContentCommand
```

I think that this is because some of the items in $Deployment are null, so it is failing to construct the $RSConfig object.

I think if you switch to something like the following it would work without error, or at least it does on my project files:

```
$RSConfig = [pscustomobject]@{
    FullPath               = $Deployment.FullPath
    OverwriteDatasets      = $Deployment.OverwriteDatasets
    OverwriteDataSources   = $Deployment.OverwriteDataSources
    TargetReportFolder     = if ($null -eq $Deployment.TargetReportFolder) { $null } else { ($Deployment.TargetReportFolder).Trimend("/") }
    TargetDatasetFolder    = if ($null -eq $Deployment.TargetDatasetFolder) { $null } else { ($Deployment.TargetDatasetFolder).Trimend("/") }
    TargetDatasourceFolder = if ($null -eq $Deployment.TargetDatasourceFolder) { $null } else { ($Deployment.TargetDatasourceFolder).Trimend("/") }
    TargetReportPartFolder = if ($null -eq $Deployment.TargetReportPartFolder) { $null } else { ($Deployment.TargetReportPartFolder).Trimend("/") }
    TargetServerURL        = $Deployment.TargetServerURL
    RsProjectFolder        = Split-Path -Path $RsProjectFile
}
```

**Comment by jtarquino** [comment]
@SQLvariant that might be able to help

**Comment by SQLvariant** [comment]
@selsine How are you expecting the subsequent command `Publish-RsProject` should handle a Null config?  For example, if the `-TargetDatasetFolder` parameter is NULL/not provided, what should `Publish-RsProject` function do if it finds Datasets in the `-RsProjectFolder` specified?

Should the `Publish-RsProject` function try to deploy the Datasets to the same location as the `-TargetReportFolder`?
Or should the `Publish-RsProject` function just skip deploying Datasets if any are found?

I think the current behavior of `Publish-RsProject` is that if you didn't anything for the `-TargetDatasetFolder` parameter it would probably attempt drop any Datasets it finds into the root of the catalog `/`.

**Comment by selsine** [comment]
Thanks for the replies, I'm honestly not sure how this should behave in that situation. I inherited this project and that was they way that they original developers had it setup. I'm just trying to use this PowerShell module to automate the deployment process on Azure.

In general I would expect it to function in the same way that Visual Studio does when you publish using it, since the settings in the project file are valid, which I think is your first option.

**Comment by robkott** [comment]
To me, if a value is not specified in the Target properties, the intent is have them deployed in the root folder, e.g., TargetDatasetFolder is null and the project has datasets, the datasets would be deployed into the root folder specified by TargetServerUrl.

In this case, whether it makes most sense to default to null, empty string or \, depends on what is easies for consuming in Publish-RsProject.

Also, I am not sure how FullPath plays into this.

**Comment by SQLvariant** [comment]
> I'm not that familiar with powershell but when I try to run Get-RsDeploymentConfig on my SSRS project file I'm getting the following error:
> 
> ```
> Get-Content : Cannot bind argument to parameter 'Path' because it is null.
> At line:1 char:29
> + [XML]$rptproj = Get-Content $RsProjectFile
> +                             ~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Get-Content], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.GetContentCommand
> ```
> 
> I think that this is because some of the items in $Deployment are null, so it is failing to construct the $RSConfig object.
> 
> I think if you switch to something like the following it would work without error, or at least it does on my project files:
> 
> ```
> $RSConfig = [pscustomobject]@{
>     FullPath               = $Deployment.FullPath
>     OverwriteDatasets      = $Deployment.OverwriteDatasets
>     OverwriteDataSources   = $Deployment.OverwriteDataSources
>     TargetReportFolder     = if ($null -eq $Deployment.TargetReportFolder) { $null } else { ($Deployment.TargetReportFolder).Trimend("/") }
>     TargetDatasetFolder    = if ($null -eq $Deployment.TargetDatasetFolder) { $null } else { ($Deployment.TargetDatasetFolder).Trimend("/") }
>     TargetDatasourceFolder = if ($null -eq $Deployment.TargetDatasourceFolder) { $null } else { ($Deployment.TargetDatasourceFolder).Trimend("/") }
>     TargetReportPartFolder = if ($null -eq $Deployment.TargetReportPartFolder) { $null } else { ($Deployment.TargetReportPartFolder).Trimend("/") }
>     TargetServerURL        = $Deployment.TargetServerURL
>     RsProjectFolder        = Split-Path -Path $RsProjectFile
> }
> ```

Thanks for the feedback.  A new version of the module is available in the PowerShell Gallery with 3/4ths of the changes you suggested.  

I did not implement the `$null` logic on `TargetReportFolder` because SSRS projects that deploy Datasets and/or DataSources without Reports are kind of rare.  I also don't think the `Publish-RsProject` function would know what to do in that scenario.  

If you are deploying an SSRS project which deploys Datasets and/or DataSources without Reports please tell me more about your scenario, so I can try to make the `Publish-RsProject` function handle things properly.

**Comment by selsine** [comment]
Thanks for the update, I've tested this and I am now able to get the config using Get-RsDeploymentConfig without issue. I am however having problems further down the chain with Publish-RSProject. Publish-RSProject may not work for us either way because we need to use a proxy, but here are the errors:

```
WARNING: Folder / does not exist
New-RsRestFolder : Cannot bind argument to parameter 'FolderName' because it is an empty string.
At C:\Program Files\WindowsPowerShell\Modules\ReportingServicesTools\0.0.6.5\Functions\Common\MakeDeploymentFolders.ps1:14 char:93
+ ... rtPortalUri $ReportPortal -RsFolder $Base -FolderName $Folder -Verbos ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-RsRestFolder], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-RsRestFolder

WARNING: Folder /Local does not exist
VERBOSE: Making call to https://localhost/Reports/api/v2.0/me to create a session...
Failed to create a new session to https://localhost/Reports/api/v2.0/me : The remote server returned an error: (401) Unauthorized.
At C:\Program Files\WindowsPowerShell\Modules\ReportingServicesTools\0.0.6.5\Functions\Utilities\New-RsRestSession.ps1:125 char:9
+         throw (New-Object System.Exception("Failed to create a new se ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Exception
    + FullyQualifiedErrorId : Failed to create a new session to https://localhost/Reports/api/v2.0/me : The remote server returned an error: (401) Unauthorized.
```

For the first warning I think you can avoid it with something like the following in Publish-RsProject line 94

```
$TargetReportFolder, $TargetDatasourceFolder, $TargetDatasetFolder | 
    Sort-Object -Unique | 
    ForEach-Object {
        if($_ -ne '/'){
            MakeDeploymentFolders -RsFolder $_ -ReportPortal $ReportPortal
        }
       
    }
```

But the second issue for us I think is related to the fact that we are using custom authentication and SSRS.  I can write out our reports using Write-RsFolderContent because I can pass a proxy with the proper authentication but I can't see how to do it with Publish-RSProject.

For our project (and I'm not an expert in SSRS in any way) we have TargetDatasetFolder and TargetReportPartFolder blank. So we don't have any datasets or report parts, but we are deploying reports.

I will try to handle it manually using Write-RsFolderContent, but I did want to update you on what I encountered.
