### ISSUE TITLE
Support -Force parameter on all commands that require confirmation

### ISSUE THREAD

**Issue by wbagdon** [microsoft/ReportingServicesTools#333]
**Do you want to request a *feature* or report a *bug*?**
Feature Request

**What is the current behavior?**
Currently `-Force` is not supported on `$PSCmdlet.ShouldProcess` functions

`Get-RsSubscription /Path/To/Item | Remove-RsSubscription -Force` fails
`Get-RsSubscription /Path/To/Item | Remove-RsSubscription -Confirm:$false` works but isn't intuitive

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
`Get-RsSubscription /Path/To/Item | Remove-RsSubscription -Force` succeeds, no confirm dialog is shown

Details on the implementation are here:
https://docs.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-shouldprocess?view=powershell-5.1#implementing--force

I am willing to create a PR for this if the feature will be accepted

**Comment by jtarquino** [comment]
Thanks, yes if you want to send a PR with the change we welcome those improvements, I recommend you also add tests in order to ensure future contributions don't cause regressions to the feature you are proposing
