### ISSUE TITLE
Installation bug - ReportingServicesTools is missing from Get-InstalledModule and unable to perform Uninstall-Module

### ISSUE THREAD

**Issue by jbelina** [microsoft/ReportingServicesTools#345]
**Do you want to request a *feature* or report a *bug*?**
Reporting an installation bug

**What is the current behavior?**
When ReportingServicesTools has been installed via one of the two Invoke-Expression methods listed in README.md, an older version number was used (see #343) and I was unable to upgrade using `Install-Module -Name ReportingServicesTools`

The error message I received indicated that there was a version collision.

_WARNING: Version '0.0.6.0' of module 'ReportingServicesTools' is already installed at 'C:\Users\jbelina\Documents\PowerShell\Modules\ReportingServicesTools\ReportingServicesTools'. To install version '0.0.6.6', run Install-Module and add the -Force parameter, this command will install version '0.0.6.6' side-by-side with version '0.0.6.0'._

With the installation in this partial state, Get-InstalledModule returned no row for ReportingServicesTools which also caused Uninstall-Module for ReportingServicesTools to fail.

_Uninstall-Package: C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:12733
 Line |
12733 |  …        $null = PackageManagement\Uninstall-Package @PSBoundParameters
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | No match was found for the specified search criteria and module names 'ReportingServicesTools'._

**Workaround**
I used the following to overwrite the installation:
`Install-Module -Name ReportingServicesTools -RequiredVersion 0.0.6.6 -AllowClobber -Force`

Afterwards, I was able to uninstall this library and then do a fresh install using the PSGallery installation source.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Uninstall the current version of ReportingServicesTools
2. Run the command `Get-InstalledModule` and verify that ReportingServicesTools is not listed.
3. Install via one of the two Invoke-Expression installation methods
`Invoke-Expression (Invoke-WebRequest https://raw.githubusercontent.com/Microsoft/ReportingServicesTools/master/Install.ps1)`
or
`Invoke-Expression (Invoke-WebRequest https://aka.ms/rstools)`
3. Rerun the command `Get-InstalledModule` and note that ReportingServicesTools is still not listed. _(It should be)_
4. Run the command `Uninstall-Module -Name ReportingServicesTools` and note the failure to in the system powershell module. _(It should not return an error)_

**What is the expected behavior?**
You should be able to uninstall the ReportingServicesTools module after installing with another method.  I'm not familiar enough with PowerShell to explain the difference between installing the module from a local copy of the install script and manifest using Invoke-Expression compared with using the PS Gallery script to perform the installation.

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
I'm a new user of the ReportingServicesTools library, however I got the same results via both pwsh v7.1.4 and powershell v5.1.19041.1023

I do not have a proposed solution for this issue.

**Comment by jbelina** [comment]
I am now using powershell v5.1.19041.1023 since I realized that New-WebServiceProxy hasn't been ported to Powershell Core.

**Comment by jtarquino** [comment]
Installing from the gallery will have the right version as it is updated during the deployment to the the gallery here https://github.com/microsoft/ReportingServicesTools/blob/313dfd660c3f573506cb9e85ec6a5ca0eb7f24c6/appveyor.yml#L139 

The pshell gallery is the preferred installation method , the options from the repo are more for development scenarios

**Comment by jbelina** [comment]
@jtarquino Would it be possible to update the README.md to reflect that PS Gallery is the preferred installation method.

Being listed as the 3rd option doesn't make it appear to be preferred.

**Comment by jtarquino** [comment]
yes, feel free to send a PR with the update
