### ISSUE TITLE
The output result of "Out-RsFolderContent" is weird

### ISSUE THREAD

**Issue by imhiteq** [microsoft/ReportingServicesTools#361]
1. use "Out-RsFolderContent" to export all items from a report server (MS SQL Server 2019) to FolderA
2. copy 1 of the reports and rename it (FolderA/reportA.rdl -> FolderA/reportB.rdl)
3. delete all other reports and keep only reportB in FolderA
3. use "Write-RsFolderContent" to upload the report (FolderA/reportB.rdl).

Upload success with a warning : "The dataset 'xxx' refers to the shared data source 'xxx', which is not published on the report server.  The shared data source 'xxx' must be published before this report can run.".

I try to download reportA by using built in portal of the report server (MS SQL Server 2019) and compare to the rdl file that download by "Out-RsFolderContent". It seems that the "path" setting of "Datasource" section is (/PathA/DatasourceA -> DatasourceA ).

Am I doing something wrong or this is a bug ?

**Comment by jtarquino** [comment]
you have to manage the dependencies manually, in case of shared datasets you need to upload the pre requisites in the right sequence and then use the command set-rsdatasetreference to point it to the location

**Comment by imhiteq** [comment]
I try to do Backup / Restore to all items on a Report Server by using "Out-RsFolderContent" and "Write-RsFolderContent". Since I have to manage the dependencies manually, I use the following step and try to figure out the dependencies.

1. use "Out-RsFolderContent" to export all items on report server to disk
2. use "Get-RsFolderContent" to list all items on report server (same as 1)

The <rd:DataSourceID> section of all RDL files that come from 1 don't match any ID which TypeName is "DataSource" that list in 2.

Do I misunderstanding the purpose (or result) of these function ?
