### ISSUE TITLE
Grant-RsSystemRole - add support for SSRS 2019

### ISSUE THREAD

**Issue by makotia-zz** [microsoft/ReportingServicesTools#362]
**bug**

**Failed to establish proxy connection to 
http://localhost/reportserver/ReportService2010.asmx : The HTML document does not contain Web service discovery 
information.**

**Imported module, then tried to Grant-RsSystemRole function**

**What is the expected behavior?** 
Be able to execute this command: Grant-RsSystemRole -Identity 'username' -RoleName 'System Administrator'

**PS version 5.1, Windows 2019, SSRS 2019, SQL 2019**

**Comment by jtarquino** [comment]
Does other commands work properly in your environment?
From the error message seems to be it can't connect to the server
