### ISSUE TITLE
SSRS and SQL Server 2008

### ISSUE THREAD

**Issue by SQLScott** [microsoft/ReportingServicesTools#363]
**Do you want to request a *feature* or report a *bug*?**
Does this work with SQL Server 2008? The reason I ask is because I cannot get the Out-RsFolderContent to work with Api version 2005 or 2006 and SQL Server 2008. Specifically, the properties of the $item do not have a TypeName, but a Type. So when it hits line 96, it never evaluates to true even when the Type is a folder. 

If this is truly a bug, I am happy to do a pull request and fix it, but just wanted to check.

![image](https://user-images.githubusercontent.com/1413382/149864495-fba89e04-314f-484a-87fb-fd931d797d8b.png)

**What is the current behavior?**
See above.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Simple, try and use the Out-RsFolderContent against a SQL Server 2008 and Api version 2005 or 2006.

**What is the expected behavior?**
It should export the reports. :-) 

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
PSVersion 5.1 on Windows 10.

**Comment by jtarquino** [comment]
It is only meant to work with the ReportService2010 endpoint which started in SSRS 2008R2

**Comment by SQLScott** [comment]
Then why does it say the following in the comments for New-RsWebServiceProxy.ps1? That comment leads me to believe it DOES support anything prior to 2008R2. If if in fact doesn't, that comment needs to change. 

![image](https://user-images.githubusercontent.com/1413382/149970967-9725f46d-9d32-4782-b833-03122138cf06.png)

**Comment by jtarquino** [comment]
Probably a good faith mistake, it was never tested with anything earlier than SSRS 2016 when it was written
