### ISSUE TITLE
Out-RsCatalogItem do not allow different format extension 

### ISSUE THREAD

**Issue by fermenreq** [microsoft/ReportingServicesTools#366]
**Do you want to request a *feature* or report a *bug*?**
Feature, enhancement
**What is the current behavior?**
It downloads a report file in rdl format but could be nice to allow different format extension (.csv, pdf,..)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Includes in `Out-RsCatalogItem` function a parameter to choose format file extension 
**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
5.0

**Comment by jtarquino** [comment]
the scope of the toolset is to provide management operations not execution operations (like render or export) however we welcome contributions to extend the original scope
