### ISSUE TITLE
New RsSubstraction

### ISSUE THREAD

**Issue by pavelmayerov** [microsoft/ReportingServicesTools#367]
Hello.
I took the code from here as an example [](https://www.powershellgallery.com/packages/ReportingServicesTools/0.0.2.9/Content/Functions%5CCatalogItems%5CNew-RsSubscription.ps1
)
`New-RsSubsctiption -reportServerUri "http://<ServerName>/Reports" -RsItem ' </Folder>' -Discription 'Email' | -schedule (New-RsScheduleXML -Weekly -DayOfWeek Monday) -subject 'Subscription Director' -to test@test.com`
Creating a request to create subscriptions to the created report. I have problems:

 The report has a parameter selection. how to register it in the script?(attach
![2022-02-16 123514](https://user-images.githubusercontent.com/99736862/154263203-ae4c1fbb-c99d-4a6b-b951-f94e968922aa.jpg)
)

**Comment by jtarquino** [comment]
There is not support in the cmdlets to pass parameters, we welcome contributions in case you are interested in add that functionality
