### ISSUE TITLE
Cannot migrate mobileReports

### ISSUE THREAD

**Issue by julitillo** [Microsoft/ReportingServicesTools#38]
**Do you want to request a *feature* or report a *bug*?**
It is a bug

**What is the current behavior?**
I copy the entire site from one server to a newer one and it copies mobile reports as folder and subfolders

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I have two servers with SqlServer 2016. In the source server I execute
`Out-RsFolderContent -ReportServerUri 'http://a04e0102/ReportServer_SQLSERVER2016' -Destination C:\tmp\company\paso -RsFolder /paso -Recurse`

and in the target server I execute 
`Write-RsFolderContent -Recurse -Path C:\intercambio\company\paso  -RsFolder /paso -ReportServerUri 'http://a04s0014/ReportServer'`

What I get in the target server is a folder with the name of the mobile report and one subfolder named contents

`SELECT * FROM [ReportServer].[dbo].[Catalog]`

 /paso
 /paso/Grafico30-30-Clientes
 /paso/Grafico30-30-Clientes/contents

**What is the expected behavior?**
I sould get a mobile report preview

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
I tried with ReportingServicesTools 0.0.0.9 and 0.0.0.15 and no one works
The source server is a Windows 10 PC with PowerShell 5.1.14393.1066
The target server is a Windows Server 2016 PC with PowerShell 5.1.14393.953

** TIPS
The first error I've got occurs when I try to export the folder in the source server:

`PS C:\WINDOWS\system32> Out-RsFolderContent -ReportServerUri 'http://a04e0102/ReportServer_SQLSERVER2016' -Destination C:\tmp\paso -RsFolder /paso -Recurse
Out-RsCatalogItem : No se puede validar el argumento del parámetro 'Destination'. El script de validación " Test-Path $_ -PathType Container" para el argumento con valor 
"C:\tmp\paso\Grafico30-30-Clientes\contents" no devolvió el resultado True. Determine por qué hubo un error en el script de validación e intente ejecutar el comando de nuevo.
En C:\Users\julio.local\Documents\WindowsPowerShell\Modules\ReportingServicesTools\Functions\CatalogItems\Out-RsFolderContent.ps1: 122 Carácter: 79
+ ... RsCatalogItem -proxy $proxy -RsFolder $item.Path -Destination $folder
+                                                                   ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Out-RsCatalogItem], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Out-RsCatalogItem`

![dir_tmp_paso](https://cloud.githubusercontent.com/assets/3116569/25372204/b23d3e58-2994-11e7-8601-b5b5d2a515c4.png)

The second time I execute the same command I get no error, but I get a new file UniversalBrand.colors

![dir_tmp_paso2](https://cloud.githubusercontent.com/assets/3116569/25372309/2f1f3336-2995-11e7-85ee-d10f8ad0990b.png)

**Comment by jtarquino** [comment]
The current version of the cmdlets doesn't support mobile reports.
However it shouldn't fail or create incorrect artifacts

**Comment by parthsha** [comment]
Please have a look at Out-RsRestCatalogItem to download mobile reports and Write-RsRestCatalogItem to upload mobile reports.
