### ISSUE TITLE
Unable to connect to remote server

### ISSUE THREAD

**Issue by hinlov** [microsoft/ReportingServicesTools#381]
Trying to execute:
**Get-RsFolderContent  –RsFolder '/Sample Reports' -Credential  Connect-RsReportServer -ReportServerUri 'http://<ReportServerName>/ReportServer'   -Verbose| Format-Table -AutoSize -Verbose**

gives the following error:

VERBOSE: Establishing proxy connection to http://<ReportServerName>/ReportService2010.asmx...
Exception calling "ListChildren" with "2" argument(s): "Unable to connect to the remote server"
At C:\Program 
Files\WindowsPowerShell\Modules\ReportingServicesTools\0.0.7.0\Functions\CatalogItems\Get-RsFolderContent.ps1:85 char:17
+                 $Proxy.ListChildren($Item, $Recurse)
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : WebException

Works on a local server; only failing when making calls to remote SSRS server, please advise.

**Comment by hinlov** [comment]
Resolved - the config file on the remote server had to be changed to <Add Key="SecureConnectionLevel" Value="3"/>.
It was set at 0 due to which remote connection was not being made.

**Comment by pitanni** [comment]
Would you be able to tell me exactly what to change? Thank you very much.
