### ISSUE TITLE
SSRS 2022 Support in "library.ps1"

### ISSUE THREAD

**Issue by DominikBraeu** [microsoft/ReportingServicesTools#394]
**Do you want to request a *feature* or report a *bug*?**
Bug/Feature
**What is the current behavior?**
Currently SSRS 2019 is mentioned as SQLServer vNext. However, we already have SQL Server 2019 as Version 15 and SQL Server 2022 as Version 16.

        /// <summary>
        /// SQL Server vNext
        /// </summary>
        SQLServervNext = 15

**What should be changed?**
Add SSRS 2019+SSRS 2022 Support to the Reportingservicenamespace in library.ps1

        /// <summary>
        /// SQL Server 2019
        /// </summary>
        SQLServer2019 = 15,

        /// <summary>
        /// SQL Server 2022
        /// </summary>
        SQLServer2022 = 16

**Comment by mhallockPcty** [comment]
This appears to stop this from working against SSRS 2022 at all with calls like `Set-RsDatabase` that take a `SqlServerVersion` as part of their argument set: you can't use a number greater that 15 right now.

https://github.com/microsoft/ReportingServicesTools/blob/95ab7f0c630e48541ddc31bab12b45d5f9364944/ReportingServicesTools/Functions/Admin/Set-RsDatabase.ps1#L143

Any chance we can get this updated?

**Comment by mhallockPcty** [comment]
Made a PR to try and get some attention from an MS dev, maybe we can get this fixed finally.
