### ISSUE TITLE
Adding Get-RsRestDataSource function

### ISSUE THREAD

**Issue by danubie** [microsoft/ReportingServicesTools#399]
**Do you want to request a *feature* or report a *bug*?**

This a request for enhancement.

**What is the current behavior?**

There is no function to fetch the content of a datasource to be linked to a report.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

To be able to read a data source definition from a folder to update a re

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

There is a function Get-RsDataSource for the SOAP style interface.

I do offer provide a PR adding a function Get-RsRestDataSource.

**Comment by jtarquino** [comment]
PR contributions are welcome, please also include a test to avoid regressions in the future by additional contributions
