### ISSUE TITLE
Receive Error Message when execute Get-RsCatalogItemRole

### ISSUE THREAD

**Issue by dannyssrs** [Microsoft/ReportingServicesTools#50]
Hello,
 I installed the latest ReportServicesTools and Execute Get-RsCatalogItemRole.
 I got this error message
New-RsCatalogItemRoleObject : Unable to find type 
[Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1tserver_ReportService2010_asmx.Policy].
At C:\Program Files\WindowsPowerShell\Modules\ReportingServicesTools\0.0.1.6\Functions\Security\Get-RsCatalogItemRole.ps1:104 char:29
+         $catalogItemRoles = New-RsCatalogItemRoleObject -Policy $pare ...
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power...010_asmx.Policy:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
Here is my command:
$ReportServerUri  = 'http://localhost/reports/ReportService2010.asmx?wsdl'
Get-RsCatalogItemRole -ReportServerUri $ReportServerUri -path '/Team' -Verbose

Thanks
/Danny

**Comment by jtarquino** [comment]
The Uri you are using is incorrect, it should be http://localhost/reportserver (you are using /reports), also if you are using localhost you don't need to specify the $ReportServerUri parameter

**Comment by dannyssrs** [comment]
Thank you very much!
I did try and getting the same error
![image 7](https://user-images.githubusercontent.com/30007998/27991251-82737e6e-6425-11e7-92ac-9ede3f0efe9d.png)

when I did not use $ReportServerUri parameter
Failed to establish proxy connection to http://localhost/reportserver/ : Failed to establish proxy connection to http://localhost/reportserver/ReportService2010.asmx : There was an error downloading 'http://localhost/reportserver/ReportService2010.asmx'.
At C:\Program Files\WindowsPowerShell\Modules\ReportingServicesTools\0.0.1.6\Functions\Utilities\New-RsWebServiceProxy.ps1:line:74 char:17
+                 t <<<< hrow (New-Object System.Exception("Failed to establish proxy connection to $([Microsoft.ReportingServicesTools.ConnectionHost]::Uri) : $($_.Exception.Message)", $_.Exception))

I think your code is default to "ReportServer" but my setup is "ReportServer16"

Thanks
/Danny

**Comment by jtarquino** [comment]
Yes the code uses defaults if the parameter is not specified
Seems to be you don't have a default configuration, please use your web service URL as the parameter, you can find it in the report server configuration manager https://docs.microsoft.com/en-us/sql/reporting-services/install-windows/configure-report-server-urls-ssrs-configuration-manager
