### ISSUE TITLE
Pester Tests

### ISSUE THREAD

**Issue by crshnbrn66** [Microsoft/ReportingServicesTools#57]
Question: 
 
I have a bunch of code I've written for SSRS that includes a full CI that I"m presently using for Native and SSRS integrated.  I'd like to share it but I'm struggling with how much I should put in my pester tests.  Can you provide a link to what your expectations for a Good pester test would include?  SSRS on the same host or SSRS native and integrated?  What is the general expectation?

**Comment by jtarquino** [comment]
Regarding this repository the expectation is to have test coverage in the same host using the existing infrastructure

**Comment by crshnbrn66** [comment]
Cool that clears it up quite a bit thank you
