### ISSUE TITLE
Write-RsFolderContent not parsing correctly

### ISSUE THREAD

**Issue by sqlchicken** [Microsoft/ReportingServicesTools#6]
When trying to deploy folders and content (recursively), the script is not building out the $parentFolder variable correctly. Have tested with nested folders locally and tried deploying both to root (e.g. / ) and to a direct folder (e.g. /folder).
![ssrs-ps-rsupload](https://cloud.githubusercontent.com/assets/13055276/19994413/69e0c10e-a224-11e6-97c4-e990f36fabe6.png)

**Comment by rgernha** [comment]
Thanks for raising the issue, I'll take a look at it

**Comment by rgernha** [comment]
Could you specify the exact command you use and the folder structure of the folder you were trying to upload? 
I haven't been able to reproduce the problem yet.

Thanks!

**Comment by sqlchicken** [comment]
Repro: create folder structure with nested items
C:\SSRS\
               \reports
                    \deptA
                     Sample.rdl
               \datasets
                Sample.rds

Write-RSFolderContent -serveruri 'http://local host/reports<http://local%20host/reports>' -path / -source c:\ssrs -recurse

Expected: deploy all folders and objects, properly nested

Actual: error creating folder on server, variable for parent folder is wrong

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by rgernha** [comment]
This should be fixed with https://github.com/Microsoft/ReportingServicesTools/commit/c46899c78ec2169f1caa24b7eee6702a667e18d5
