### ISSUE TITLE
Initialize-Rs fails on Azure SQL Server 2014 SP2 on Windows Server 2012 R2 (SQL2014SP2-WS2012R2)

### ISSUE THREAD

**Issue by pkleanthous** [Microsoft/ReportingServicesTools#61]
Hi, I'm trying to initialize an Azure SQL instance and I'm getting the following error:

```
> Initialize-Rs -ReportServerVersion 12 -Debug -Verbose
VERBOSE: Initializing Report Server...
VERBOSE: Success!
Failed to Initialize Report Server, Errocode: -2146233088
At C:\Program Files\WindowsPowerShell\Modules\ReportingServicesTools\0.0.2.4\Functions\Admin\Initialize-Rs.ps1:70 char:9
+         throw "Failed to Initialize Report Server, Errocode: $($resul ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to Initi...de: -2146233088:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to Initialize Report Server, Errocode: -2146233088
```

Database and URL endpoints have been configured correctly.
Is there a way to get some more meaningful error logs to isolate the issue?

**Comment by jtarquino** [comment]
You can check the logs of Reporting Services.
BTW we don't support Azure SQL Database as a catalog for Reporting Services

**Comment by pkleanthous** [comment]
@jtarquino It's a VM with SQL DataBase engine and SSRS pre-installed. So it just needs the relevant configuration for SSRS service.

Where can I find the logs? At 

> C:\Program Files\Microsoft SQL Server\MSRS12.MSSQLSERVER\Reporting Services\LogFiles
?

More info: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/Microsoft.SQL2014SP2-WS2012R2?tab=Overview

**Comment by jtarquino** [comment]
Cool, just wanted to be sure.
Indeed that is the location of the logs for SSRS 2014

**Comment by pkleanthous** [comment]
It seems that is an authentication error `Login failed for user 'NT SERVICE\ReportServer'`

```
library!DefaultDomain!5e0!08/07/2017-15:23:00:: e ERROR: Throwing Microsoft.ReportingServices.Library.ReportServerDatabaseUnavailableException: , Microsoft.ReportingServices.Library.ReportServerDatabaseUnavailableException: The report server cannot open a connection to the report server database. A connection to the database is required for all requests and processing. ---> System.Data.SqlClient.SqlException: Cannot open database "ReportingServer" requested by the login. The login failed.
Login failed for user 'NT SERVICE\ReportServer'.
```

**Comment by jtarquino** [comment]
That means your network service account doesn't have permissions in the database , double check the parameters of your call to Set-RsDatabase.ps1 before the initialization, focus in the DatabaseCredential parameter

**Comment by pkleanthous** [comment]
Hi @jtarquino thanks for the input.

I have fixed the authentication issue although the command still fails due the following error:
```
library!DefaultDomain!7a4!08/08/2017-10:05:58:: e ERROR: Throwing Microsoft.ReportingServices.Diagnostics.Utilities.OperationNotSupportedException: , Microsoft.ReportingServices.Diagnostics.Utilities.OperationNotSupportedException: The feature: “Scale-out deployment” is not supported in this edition of Reporting Services.; 
```

Does the `Initialize-Rs` command configure the scale out settings in the background?

**Comment by pkleanthous** [comment]
Okay, I figure out that I'm using a different edition locally from what I have on Azure.
Is there a way to parametrize Initialize-Rs so based on the version to include or exclude the scale out config?

**Comment by jtarquino** [comment]
What editions are you using?

**Comment by pkleanthous** [comment]
Locally I use enterprise evaluation edition to develop the provisioning scripts. On Azure standard edition.
