### ISSUE TITLE
[Feature] Read Error Log files

### ISSUE THREAD

**Issue by cankaya07** [Microsoft/ReportingServicesTools#63]
This is new feature request.

I need to read error log for current reporting services on disk. I am not a powershell expert. what do you think about it ? i uploaded which i using script right now. 

I am combining all errorlog and inserting datawarehouse db. After that analysis services powerbi etc. visualizing jobs. i think it would be a great feature.

**Comment by jtarquino** [comment]
Sounds like a nice feature to add, you don't have to be an expert to contribute, feel free to start with something small and build on top of that
