### ISSUE TITLE
Error in Backup-RsEncryptionKey

### ISSUE THREAD

**Issue by djeepy1** [Microsoft/ReportingServicesTools#65]
I get an error using Backup-RsEncryptionKey

```
Erreur: Espace de noms non valide « root\Microsoft\SqlServer\ReportServer\RS_PBIRS\v13\Admin »
Dans le fichier C:\Users\I212027_SVA\Desktop\ReportingServicesTools\Functions\Utilities\New-RsConfigurationSettingObject.ps1 (ligne 100)
    $wmiObjects = Get-WmiObject @getWmiObjectParameters
```
Which can be translated as "invalid namespace"

I ran that command 

`Backup-RsEncryptionKey -Password $password -KeyPath "f:\temp\Clé-Chiffrement$env:computername.snk" -ReportServerInstance $global:PBIRSInstanceName`
PBIRSINstanceName => "PBIRS"

Did I miss something ?

Powershell version 4 / Windows Server 2012 R2 Standard French
Power BI Report Server - June GA

**Comment by jtarquino** [comment]
The default version is for SSRS 2016, you need to add -ReportServerVersion SQLServer2017 for the new wmi namespace
