### ISSUE TITLE
Question for New-RsDataSource script

### ISSUE THREAD

**Issue by pkleanthous** [Microsoft/ReportingServicesTools#70]
Is there a way to pass the User password as a parameter?

**Comment by ClaudioESSilva** [comment]
You can ask for the credentials using `Get-Credentials` and use the variable like the following example:

```PowerShell
$newRSDSCredential = Get-Credential -Message "Enter user credentials for data source"
New-RsDataSource -ReportServerUri $reportServerUri .... -DatasourceCredentials $newRSDSCredential

```

**Comment by pkleanthous** [comment]
@ClaudioESSilva Thanks for the reply.

I would like to script it out in order to automate the process, so I would like to avoid any prompts or manual inputs.

**Comment by ClaudioESSilva** [comment]
Somehow I previewed that.

I don't recommend that you use clear text passwords on your scripts but here you have an example: 
[Working with Passwords, Secure Strings and Credentials in Windows PowerShell](https://social.technet.microsoft.com/wiki/contents/articles/4546.working-with-passwords-secure-strings-and-credentials-in-windows-powershell.aspx)

my suggestion instead is to use the method where you first save the credential (encrypted) on disk and them you can import from it and use it wherever you want you can find an example here:
[Quickly and securely storing your credentials – PowerShell](http://www.jaapbrasser.com/quickly-and-securely-storing-your-credentials-powershell/)

**Comment by pkleanthous** [comment]
@ClaudioESSilva Thanks closing the ticket
