### ISSUE TITLE
Write-RsFolderContent don't support uploading a Shared DataSource file (.rds)

### ISSUE THREAD

**Issue by adolande** [Microsoft/ReportingServicesTools#74]
Hi, 

issue #24 (https://github.com/Microsoft/ReportingServicesTools/issues/24) is closed, but Write-RsFolderContent still don't support uploading a Shared DataSource file.

In Write-RsFolderContent.ps1, the ".rds" extension is not in this test :

if ($item.Extension -eq ".rdl" -or
                $item.Extension -eq ".rsds" -or
                $item.Extension -eq ".rsd")

**Comment by parthsha** [comment]
Can you please pull the latest version of this project and try again?

**Comment by parthsha** [comment]
I am closing this issue as the issue has been resolved and I have not heard back on this issue lately.
