### ISSUE TITLE
Allow setting of properties on report (Hide in Tile View)

### ISSUE THREAD

**Issue by nschonni** [Microsoft/ReportingServicesTools#76]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Property setting is available for DataSources, but not others. This may be the last bit of custom functionality we have in our own SSRS library that I haven't seen in here. Could probably PR something if there is intereset 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Ability to set the RDL properties like https://stackoverflow.com/a/32565307/455535

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
PS 3+, new feature

**Comment by jtarquino** [comment]
We welcome any contribution, feel free to send a PR anytime
