### ISSUE TITLE
Write-RsFolderContent 'The item already exists'

### ISSUE THREAD

**Issue by davesbrown** [Microsoft/ReportingServicesTools#78]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Failed to create catalog item from
'D:*****' in
'/Carsnet.Reports/DM': System.Exception: Failed to create catalog item: Exception calling "CreateCatalogItem" with "7"
argument(s): "The item '******' already exists. --->
Microsoft.ReportingServices.Diagnostics.Utilities.ItemAlreadyExistsException: The item
'******' already exists." ---> System.Management.Automation.MethodInvocationException:
Exception calling "CreateCatalogItem" with "7" argument(s): "The item '******' already exists.

(redacted sources and paths)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Write-RsFolder -ReportServerUri 'http:/mySSRS' -Path c:\myreports -RsFolder /foldertopublishto

**What is the expected behavior?**

I think maybe a -Force or -Overwrite parameter is needed to overwrite existing reports?

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
PS 5
Windows 10 local, 2012 SSRS
First time trying this cmdlet

**Comment by markwragg** [comment]
`Write-RsCatalogItem` has a -Overwrite switch already, so I think this issue can be addressed by just adding the same switch to `Write-RsFolderContent` and passing it through.

**Comment by markwragg** [comment]
PR https://github.com/Microsoft/ReportingServicesTools/pull/80 raised to fix.

**Comment by markwragg** [comment]
I've had to reraise the PR that I raised to fix this issue as the previous one inadvertently included other changes. Now that my more significant PR has been merged I've now put forward a PR for this fix. https://github.com/Microsoft/ReportingServicesTools/pull/90
