### ISSUE TITLE
Initialize-Rs  - unsure about syntax

### ISSUE THREAD

**Issue by gorkam23** [Microsoft/ReportingServicesTools#81]
The help file does not have any examples, but I looked at the function code and figured out the parameters.

Here is what I put in:

Initialize-Rs -ReportServerInstance 'MSSQLSERVER' -ReportServerVersion '12' -ComputerName 'vanl-jjf4362'

I received this error:

Get-WmiObject : The RPC server is unavailable.

I may very well be doing something wrong, but I am just not sure.

Thanks!

**Comment by jtarquino** [comment]
Are you trying to do it remotely , if that is the case your remote server need to have the WMI ports open, give it a try allowing the ports in the firewall or running it locally

**Comment by gorkam23** [comment]
No, I'm not doing it remotely.  THis is all on my PC.

**Comment by jtarquino** [comment]
Try without the computer name, also check your service is started (you can verify it opening the Reporting Services config tool and connecting to the server)

**Comment by gorkam23** [comment]
Ok, thanks.  I will try that.  I am trying to make all of the new RS functions work.  I understand that without a  2016 SSRS install I will not have complete success.
