### ISSUE TITLE
Bug with Set-RsDataSourcePassword

### ISSUE THREAD

**Issue by gorkam23** [Microsoft/ReportingServicesTools#82]
THis is all performed on a local PC using an admin account.  

The specific error message appears to be:  The combination of values for the fields Password and CredentialRetrieval are not valid.  

If I am making a mistake here, please enlighten me.  I get the same error when I do put in the credential
![set-rsdatasourcepassword_stillnotworking](https://user-images.githubusercontent.com/32223642/31587034-f0f91284-b18e-11e7-93d4-3fb4dfaaabc3.png)

My command -

Set-RsDataSourcePassword -ReportServerUri 'http://vanl-jjf4362/reportserver' -Path /BOB/BOBDS -verbose -debug

Thank you.

**Comment by jtarquino** [comment]
Check the documentation of SetDataSourceContents 
https://msdn.microsoft.com/en-us/library/reportservice2010.reportingservice2010.setdatasourcecontents.aspx
The data source can't be integrated or prompt when you specify credentials

**Comment by jzabroski** [comment]
So,

```
$ds = Get-RSDataSource -ReportServerUri "http://localhost/ReportServer" -Path /BOB/BOBDS
$ds.CredentialRetrieval = [CredentialRetrievalEnum]::Store
$ds.WindowsCrendetials = $false
$ds.Prompt = null
$ds.UserName = "JohnDoe"
$ds.Password = "JaneDoe"
Set-RSDataSource -ReportServerUri "http://localhost/ReportServer" -Path /BOB/BOBDS
```

?

**Comment by gorkam23** [comment]
Bear with me here.  I want to be sure I'm understanding the purpose of the command Set-RSDataSourcePassword.    Also, remember I am doing this all on SSRS 2014.

When I change the password, is it supposed to be able to go back and change it at the SQL Server security layer?

I was able to get the command to take without error, but I have no idea what it changed.

Set-RsDataSourcePassword -ReportServerUri 'http://vanl-jjf4362/reportserver' -Path /BOB/BOBDS -Password bob2

This is to change the password for the Datasource BOBDS in the folder BOB.

Here is the output from Get-RsDataSource:

![image](https://user-images.githubusercontent.com/32223642/31784559-fe78834c-b4b6-11e7-9d82-e7d15907f2a6.png)


thank you!

**Comment by jzabroski** [comment]
Your use of the phrase change is strange. These scripts are used by me personally for a continuous integration / continuous delivery pipeline with Octopus Deploy. I don't really think in terms of "change" so much as "desired state" that is "required to be met to consider deployment a success".

**Comment by gorkam23** [comment]
When I Set the password, isn't it Changing it?  

What is the point of the function if I'm missing it?

Thanks!

**Comment by jt000** [comment]
The Set-RSDataSourcePassword is to change the password that is stored in the reporting service data source catalog item. It doesn't change the password that is referenced by the data source, which could be a SQL Server connection, Oracle connection, SOAP connection, etc... If your Reporting Services Data Source doesn't have a stored password (as in the case when it is set to prompt the user viewing a report for a password or to use the user's integrated windows credentials) then you will not be able to save a password using this method (there should be no need).

**Comment by gorkam23** [comment]
Ok, then I do believe I am trying to use the command the appropriate way.  

In the aforementioned example, my datasource BOBDS has a stored user and password of bob/bob

I was attempting to use Set-RSDataSourcePassword to change the stored password to bob2

While the command appeared to run normally, the password did not change.  

This could be because I am doing this on a SSRS 2014 instance.

Thank you!

**Comment by jt000** [comment]
That is interesting... SSRS 2014 should work the same as newer versions since the cmdlet is using the 2010 SOAP endpoints. I'd suggest checking the report server logs to see if something is reported there. Where are you seeing that the password wasn't changed? (it shouldn't be visible in plain text anywhere)

**Comment by gorkam23** [comment]
Oh, just by putting in the new password and clicking on the Test Connection button.

**Comment by jzabroski** [comment]
I think you are confusing configuration of a data source, with actually changing a login's password (or even creating a new login with such a password). These are two separate tasks.  The configured data source will be encrypted, and so the purpose of both the Web UI to create Data Sources w/ passwords as well as this projects' Set-RSDataSourcePassword is merely configuration so that the "data at rest" configuration is encrypted and cannot be stolen once configured.

Hope that helps.

**Comment by gorkam23** [comment]
That does make sense and I knew something was not right there.  I am just not used to encrypted data sources I think.  I will experiment later then.  Thank you!
