### ISSUE TITLE
Bug with Set-RsEmailSettings

### ISSUE THREAD

**Issue by gorkam23** [Microsoft/ReportingServicesTools#83]
Local PC - admin account - SSRS 2014 - Version 0.0.2.8 RS tools.

Is this a syntax error?

![set-rsemailsettings_notworking](https://user-images.githubusercontent.com/32223642/31587132-ceb97dec-b190-11e7-8a9b-f087214c3a70.png)

**Comment by jtarquino** [comment]
This function will only work with 2016 and newer were we introduced the ability to specify a password for the email account
Previous versions only support email with integrated auth

**Comment by gorkam23** [comment]
Ok, thank you.  I will close it then.
