### ISSUE TITLE
New-RsFolder  Item already exists

### ISSUE THREAD

**Issue by davesbrown** [Microsoft/ReportingServicesTools#89]
What exception to catch when using the New-RsFolder cmdlet if the folder already exists? 

> Unable to find type [Microsoft.ReportingServices.Diagnostics.Utilities.ItemAlreadyExistsException]

Is there check for existence, or another cmdlet to use for existence such as Get-RsFolder ?

**Comment by markwragg** [comment]
It looks like the exception type to use for this error is actually `System.Exception`, which is annoyingly generic. 

This blog post from Boe Prox has good guidance on how to identify the exception for an error: https://learn-powershell.net/2015/04/09/quick-hits-finding-exception-types-with-powershell/

I had a play also with `Get-RsChildItem` and it throws a `System.Management.Automation.MethodInvocationException` exception when a folder doesn't exist, which is also pretty generic.

**Comment by jzabroski** [comment]
Just support -Force and make all the code examples use -Force.
-Force should ensure the folder exists
-Force -Verbose should warn about pre-existing permissions staying.

My current workaround is -ErrorAction Continue which is not ideal since it will suppress weak or episodic connectivity issues, services in middle of restarting, services down, etc.

**Comment by parthsha** [comment]
I would prefer introducing a new switch like Overwrite instead of using Force. This is also something we have done in several places like New-RsDataSource, Set-RsDataSourcePassword, Write-RsCatalogItem, Write-RsFolderContent.

**Comment by parthsha** [comment]
@davesbrown you can do something like the following. I am curious to hear on your thoughts. 

$targetFolder = Get-RsFolderContent -RsFolder "<parent folder>" | Where-Object { $_.Name -eq "<target folder name>" }
if ($targetFolder -eq $null) 
{
     New-RsFolder -FolderName "<target folder>" - RsFolder "<parent folder>"
}

**Comment by parthsha** [comment]
I am going to close this issue. If you have any further questions, please feel free to open it again.

**Comment by davesbrown** [comment]
I'm back on a new server deployment and this issue arose again and I found this thread.  @parthsha  I'll try your suggestion.  Meanwhile here is what I was about to post as new issue:


**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
New-RsFolder throws a wrapped exception even for if item exists, 
    catch
    {
        throw (New-Object System.Exception("Exception occurred while creating folder! $($_.Exception.Message)", $_.Exception))
    }

How about adding a catch for this
Microsoft.ReportingServices.Diagnostics.Utilities.ItemAlreadyExistsException:
for a graceful break

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

New-RsFolder -RsFolder '/' -FolderName 'My new folder'
when FolderName already exists

**What is the expected behavior?**
A specific catch for existing item, or Get-RsFolder helper function to test existence?

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
5.1 Win2016 Sql2017

**Comment by davesbrown** [comment]
@parthsha this seems to work

    try {
        $targetFolder = Get-RsFolderContent -RsFolder $RsFolder | Where-Object { $_.Name -eq $FolderName }
        if ($null -eq $targetFolder) {
            New-RsFolder -ReportServerUri $ReportServerUriArray -RsFolder $RsFolder -FolderName $FolderName
        }
        else {
            Write-Output 'RsFolder already exists'
        }
    }
