### ISSUE TITLE
Write-RsCatalogItem.ps1 suppresses $warnings, even in -Verbose mode

### ISSUE THREAD

**Issue by jzabroski** [Microsoft/ReportingServicesTools#91]
$warnings is assigned via a [ref] but is not output, even in -Verbose mode.

As I explain in my pull request, this appears to be a much bigger problem than I first thought, as apparently the 2016 Reporting Services endpoint I am testing against silently fails to actually create the report.

**Comment by parthsha** [comment]
Thank you very much for submitting the fix for this issue! I am going to close it now.
