### ISSUE TITLE
Write-RsCatalogItem does not check return value of $Proxy.CreateCatalogItem

### ISSUE THREAD

**Issue by jzabroski** [Microsoft/ReportingServicesTools#93]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
If the .rdl file being written to the report server's catalog has an invalid data source (e.g. one that has not yet been uploaded), then the report server will not create a CatalogItem but will populate the Warnings [out] collection as vaguely documented here: https://msdn.microsoft.com/en-us/library/reportservice2010.reportingservice2010.createcatalogitem.aspx The docs say "If errors occur, the item is not created." The C# code example is equally vague, as it does not check the returned CatalogItem object's value, but the cod example does suggest catching SoapException.

In ReportingServicesTools Write-RsCatalogItem, currently, CreateCatalogItem result is piped to Out-Null and not checked for a non-null reference.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Edit an RDL file to point to a bogus DataSourceReference (or one that does not exist yet), and call Write-RsCatalogItem on the RDL file.

**What is the expected behavior?**
Some way to alert the client programmer that the report did not get uploaded successfully.

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

```
PS C:\> $PSVersionTable

Name                           Value                                                                                                                                                                                                 
----                           -----                                                                                                                                                                                                 
PSVersion                      5.1.15063.483                                                                                                                                                                                         
PSEdition                      Desktop                                                                                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                               
BuildVersion                   10.0.15063.483                                                                                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                   
SerializationVersion           1.1.0.1                                                                                                                                                                                               
```

**Comment by parthsha** [comment]
I am not a huge fan of creating bogus or fake data sources. The correct fix for this issue is to first create all the (shared data source/set) dependencies of the report and then upload the report. Unfortunately, there is no easy way to do this, so the responsibility of this should really be on the user of this command. However, I agree that an error should be thrown when this occurs, so I am willing to make it more easier to discover whenever this happens. Is this something you are okay with it?

**Comment by parthsha** [comment]
@jzabroski I tried this out today and while I am seeing the warnings, my report got uploaded just fine. When I went to portal and looked at the report properties, I see the data source is pointing to nothing, which is what I expected. Do you have a sample report which doesn't get created at all?

**Comment by parthsha** [comment]
Closing this issue as I was not able to repro it myself. Please reopen it if you continue to experience this.
