### ISSUE TITLE
New-RsDataSource does not check return value of CreateDataSource

### ISSUE THREAD

**Issue by jzabroski** [Microsoft/ReportingServicesTools#95]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Silently fails to create a data source if the -RsFolder does not exist.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Please see https://msdn.microsoft.com/en-us/library/reportservice2010.reportingservice2010.createdatasource.aspx
If errors occur, the data source is not created.

Passing in an invalid -RsFolder causes the problem.

**What is the expected behavior?**
Raise an error.

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
```powershell
PS C:\> $PSVersionTable

Name                           Value                                                                                                                                                                                                 
----                           -----                                                                                                                                                                                                 
PSVersion                      5.1.15063.483                                                                                                                                                                                         
PSEdition                      Desktop                                                                                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                               
BuildVersion                   10.0.15063.483                                                                                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                   
SerializationVersion           1.1.0.1             
```

**Comment by parthsha** [comment]
I am seeing the following exception when I specify a value to -RsFolder that does not exist.

Exception occurred while creating data source! Exception calling "CreateDataSource" with "5" argument(s): "System.Web.Services.Protocols.SoapException: The item '/nonexistent'
cannot be found. ---> Microsoft.ReportingServices.Diagnostics.Utilities.ItemNotFoundException: The item '/nonexistent' cannot be found.

**Comment by jzabroski** [comment]
I will try reproducing with a full example.  Can you send me your repro example? I am wondering if when I was troubleshooting the problem, I was connected to the wrong server. Is it possible fixing another bug recently made this problem go away? This was on 0.0.2.9

**Comment by parthsha** [comment]
I created a data source and then re-ran the same command. I got the error above. I am not sure if anything else would have fixed this bug or not.

**Comment by parthsha** [comment]
Closing issue as I am not able to repro this issue and haven't heard back on it continuing to occur.
