### ISSUE TITLE
Create tutorial with some best practices

### ISSUE THREAD

**Issue by jzabroski** [Microsoft/ReportingServicesTools#98]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
The README.md file lists all the APIs, but I think there is a fairly standard way to structure things that is unexplained in the existing README, and think it would help save everyone time if that structure was canonicalized in some quality example code. Such quality example code could then feed into Issue #84 - once people can see a standard approach to setting up a reporting environment, they can also see how a fully parameterized approach can be plugged into Octopus Deploy via a step template.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
People should be able to copy and paste code, it just works, then go drink a [beer.](http://www.99-bottles-of-beer.net/language-powershell-1851.html)

**Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**
n/a - documentation/tutorial

**Comment by jtarquino** [comment]
We have tried to document and add examples to the functions (in each one) instead of a general demo which might leave out the newer functions. Having said that we welcome contributions from the community and it will be great if want to add such feature
